### ISSUE TITLE
Extends #16 FAQ and #15 Recognizing

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#100]
- Extends #16
- Removes "Question:" and "Answer:" from accordions
- Uses [`usa-tag` USWDS pattern](https://designsystem.digital.gov/components/tag/) in place of "IBA" and "CBA" in questions

References original content design prototype in [🔒 this doc](https://docs.google.com/document/d/1H0_WIXSQnXlyWBi767pVaPi6aSuRF3h8sVUCnguU3ag/edit?usp=sharing)

![Frequently asked questions with accordion style](https://user-images.githubusercontent.com/32855580/221097599-aeb27c6c-8eec-41bc-8b4b-7624bdad8af2.png)

**Comment by weiwang-gsa** [comment]
@brentryanjohnson for below section, where it needs to be position at Recognizing your charge card page? Under Travel Card or different section? 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/119954777/221661668-f92a2a3f-4554-4f7c-85e1-5e58dd8cf011.png">

**Comment by weiwang-gsa** [comment]
@A-L33 The top navigation buttons for recognizing charge card page is just test implementation options that used for your discussion with Ryan for navigation structure, it only can navigate to section, but if you are the bottom, you still need to scroll up to see other sections, if it is ok for you, can I remove this testing implementation ? Also as Mark just pointed out, it doesn't meet USWDS guidance for button usage, we may need to find alternative solutions, and it will be better tracked as separate issue as it is global for pages that are really long. 

![Image](https://user-images.githubusercontent.com/119954777/221944868-74c40c12-404f-4835-a92d-2b5fc2ec1c70.png)



![Image](https://user-images.githubusercontent.com/119954777/221945083-35d42771-0aad-438f-95d1-8d6045b7ebcc.png)

**Comment by A-L33** [comment]
@weiwang-gsa @johnbeallgsa Let's remove it and find alternatives.  If you have a suggestion for tracking this as a separate issue, please let us know.  We're happy to log it.

**Comment by weiwang-gsa** [comment]
@A-L33 Thanks for confirmation. I will remove the top button navigation. USWDS has in page navigation, but it kinda conflicts with current side navigation,  If in page navigation is very important to you for long articles, you can log a separate issue for exploring possibility. It may involves design or nav change.

**Comment by johnbeallgsa** [comment]
Confirmed the top button navigation is no longer there.   Will log an additional story for in-page navigation.
