### ISSUE TITLE
State tax | Legal History

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#11]
Path: smarttax/legal-history
File name: 
Design: [State Tax Info > Legal History](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A43424&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

**NOTE:** This has already been implemented; may need to re-visit based on updated design.

Content: https://smartpay.gsa.gov/content/legal-history) which provides:
   - Information about why a single form cannot be used for sales tax exemption
   - Legal history and Supreme Court case decisions
   - Explanation of payment liability in determining tax exemption eligibility

**Comment by JessicaMarine1** [comment]
Does this content need to be updated?

**Comment by weiwang-gsa** [comment]
Ready for QA review : https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/legal-history/

Please focus content verification. The site navigation and general look and feel of site is out scope of this issue. It may be changed at later stage after redesign  of issue #12 is finalized.

**Comment by A-L33** [comment]
@weiwang-gsa Please replace the following links:

- Supremacy Clause of the U.S. Constitution with this:  https://www.archives.gov/founding-docs/constitution-transcript
- McCulloch v. Maryland, 17 U.S. 316 (1819) with this:  https://www.archives.gov/milestone-documents/mcculloch-v-maryland

**Comment by weiwang-gsa** [comment]
@A-L33 links are updated, ready for review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/legal-history/

**Comment by brentryanjohnson** [comment]
I noticed some stylistic inconsistencies (e.g. "U.S." versus "US") and some possible errors. I've added some [editorial suggestions in this 🔒 google doc](https://docs.google.com/document/d/1fXDv-aZiZe2n6zfvsUQQR4CVvjJcYjgjVXjKtzKZ6iY/edit?usp=sharing).

**Comment by weiwang-gsa** [comment]
@brentryanjohnson would you mind granting me access to review the google doc? Thanks!

**Comment by A-L33** [comment]
I just shared the google doc with @weiwang-gsa .  @brentryanjohnson I am good with the suggestions you provided.  Would you like to meet with me and @johnbeallgsa really quickly tomorrow to discuss the other observations before Wei pulls the language in?

**Comment by A-L33** [comment]
@brentryanjohnson Content ready for your review.

**Comment by A-L33** [comment]
@weiwang-gsa Good to go!

**Comment by weiwang-gsa** [comment]
@A-L33 below are the modification made:

1.Removed banner hero image ( per Ryan's suggestion in previous meetings, we only include hero image for home page, and this is content page, @brentryanjohnson please correct me if my understanding is wrong. )
2.Made content adjustment based on [Ryan's doc](https://docs.google.com/document/d/1fXDv-aZiZe2n6zfvsUQQR4CVvjJcYjgjVXjKtzKZ6iY/edit?usp=sharing)

You can pre-review my code change here: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/wwang-issue11/smarttax/legal-history/

Please let me know if you are ok with the changes. If yes, I will created PR request for code changes and merge into main branch after code review.

**Comment by A-L33** [comment]
@weiwang-gsa Looks good!  Moving to Done.  First one!  Thank you!

**Comment by mark-meyer** [comment]
@klohman I think this is ready for design review:

https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/legal-history/

**Comment by klohman** [comment]
@rebekahperillo Ready for QA review.

**Comment by rebekahperillo** [comment]
@A-L33 State taxes again. :) Would you like to review/approve?

**Comment by A-L33** [comment]
Done!
