### ISSUE TITLE
Add ability to zoom images

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#122]
The SmartPay program website contains a few images that include substantial text and infographics. [There's an example of such an image on this page](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-about-1/about/how-gsa-smartpay-works/).

Currently, the text in the diagram is illegible at the rendered image proportions. A user would have to open the image in a new tab (or open the alt text) to comfortably read the text in the image.

We should consider a design pattern that allows the user to zoom the image, or otherwise render images at a size that makes text legible.

**Comment by JessicaMarine1** [comment]
@melchoyce @klohman this looks like a request for a specific design pattern. Please confirm whether this has been taken into account in the prototype/design.

**Comment by brentryanjohnson** [comment]
We can close this one for now. This was related to the infographic we replaced with the USWDS process list.
