### ISSUE TITLE
Government Shutdown FAQs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#125]
Path: 
File name: 
Design: 
Template:
_______________ 
As an A/OPC or cardholder, I want easy access on this website to common questions about using my card during government shutdown I might have, so I don't have search the entire website or contact customer service.

Acceptance criteria

- User is presented with content from https://docs.google.com/document/d/1QcSvTOiyMgZ41geMg-GyX6bdITKAPkLdA85WQzcOuGo/edit#
- Content in accordions is searchable even in its collapsed state. The USWDS component demo doesn't seem to allow for this OOTB, but the [ada.gov](http://ada.gov/) implementation does support search in accordions: https://www.ada.gov/topics/intro-to-ada/#the-ada-prohibits-disability-discrimination-in-many-areas-of-life

**Comment by JessicaMarine1** [comment]
@brentryanjohnson This is ready for your review. Please note there are 2 sections: one for cardholders and one for A/OPCs

**Comment by brentryanjohnson** [comment]
✅ Reviewed

**Comment by JessicaMarine1** [comment]
Accepted all recommended changes. Moving to `Content Final & Ready`

**Comment by JessicaMarine1** [comment]
Moved to #16
