### ISSUE TITLE
State tax | Exemption Information

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#13]
As a stakeholder in a charge card transaction, I need to find tax exemption information for each of the 50 states, 5 territories, and District of Columbia, so that I know whether or not the government is eligible for State sales tax exemption in a specific locale.

**Acceptance criteria:**

- User can search for state tax exemption eligibility information for each of the 50 states, 5 territories, and District of Columbia
- User can access specific tax exemption laws, regulations, and policies for each State, territory, and district
- User can differentiate results based on information for individually billed solutions and centrally billed solutions
- User can differentiate information available for Purchase, Travel (i.e., CBA, IBA, and Travel Tax Advantage), and Integrated solutions, if it is available
- User is provided the State revenue office points of contact for additional inquiry

Content: https://docs.google.com/document/d/14nNOfoL_j-gfv-e0QR8J-ukdnT7J1NDdWAJUR0Xs2Kk/edit

**Comment by JessicaMarine1** [comment]
Discuss with dev team whether this story needs to be broken up?

**Comment by weiwang-gsa** [comment]
This issue is close related to #12 and #14, once the #12 state tax findability redesign is finalized, we will have better idea where this content will be placed

**Comment by A-L33** [comment]
Individual state tax information updated and ready to go here:  https://docs.google.com/document/d/14nNOfoL_j-gfv-e0QR8J-ukdnT7J1NDdWAJUR0Xs2Kk/edit

**Comment by A-L33** [comment]
@brentryanjohnson Content is ready for your review.

**Comment by brentryanjohnson** [comment]
@A-L33 We started adding this to the repo last week using [🔒 this format](https://docs.google.com/document/d/15oIhXBWT7QLkRECzZK8wdwayioatTiXZhO6FzhLOqVw/edit?usp=sharing). I'll check the most recent updates!

**Comment by brentryanjohnson** [comment]
@jfredrickson5 It looks like the only update is to Illinois.

**Comment by A-L33** [comment]
Apologies, I made a quick update to Illinois because I found new information.  Thank you!

**Comment by vickimcfadden** [comment]
Replicate the design of GSA.gov with dropdown by state (in alphabetical order): https://www.gsa.gov/travel/plan-book/state-tax-exemption-information-for-government-charge-cards?_ga=2.120424204.586479946.1676399924-1523180152.1676399924#/state/louisiana

Note: no map needed now (for accessibility reasons and for people like vicki who can't find states on a map)

**Comment by A-L33** [comment]
@jfredrickson5 @brentryanjohnson Good morning!  Looks like the State of Washington changed its phone number structure.  The new phone number for the Washington Department of Revenue is 360-705-6705.  Thank you!

**Comment by JessicaMarine1** [comment]
- Do we want to use the clickable states – where each state has own page/URL (better for analytics and google searches) or the dynamic dropdown where the info populates beneath

- Discussed pros/cons of each

- Mark suggested having the dropdown direct to a standalone page where the dropdown persisted

- Decision: For this sprint, going to go with the dynamic dropdown where the info populates beneath. Will add new story to consider moving to standalone pages

**Comment by A-L33** [comment]
@weiwang-gsa @mark-meyer @jfredrickson5 @brentryanjohnson Looks like GSA.gov (content scraped from SmartPay) may have a different URL for the drop down?  Thoughts?  https://www.gsa.gov/travel/plan-book/state-tax-exemption-information-for-government-charge-cards?_ga=2.120424204.586479946.1676399924-1523180152.1676399924#/state/district-columbia

**Comment by weiwang-gsa** [comment]
@A-L33 just to your question, that is actually not separate URL, the link up to question mark ? is the URL portion, the rest are the argument info attached to the URL that code use it for display certain state for the user selection ( like query string parameter values) . The URL is actually the same. For state tax info (#14), I will do following: 

- Fix navigation
- Implement drop down list with state section hide and show
- Adding rest of states data ( currently only have 4) 

Honestly my effort for dropdown list with hide and show states are already there. so there is no waste because efforts already been made. I will test the dropdown list selection change leading to separate URL at the end once I am done with above.

**Comment by weiwang-gsa** [comment]
@A-L33 Actually issue 13 is for exemption information, what does this piece go? this part of text should be in the top section for the state-tax-information page, just before the dropdown list?

**Comment by brentryanjohnson** [comment]
@A-L33 Do we still need both this issue (13) and #14? I think they're the same scope of work, unless I'm missing something?

**Comment by A-L33** [comment]
@brentryanjohnson Short answer, we probably don't need 13 and 14 or we can combine them.  When we scoped this out before, it made sense to separate them.  But based on the form/template you came up with, we can combine or close one of these out.

**Comment by weiwang-gsa** [comment]
@A-L33 , I orginally thought you want to put some exemption information text above the drop downlist, so I made the change below, but after talking to Ryan, he said I don't need to add this text at all. lol, in this case, I think we probably should close #13 to void confusion.

![Image](https://user-images.githubusercontent.com/119954777/221045921-103451f8-4410-4fa7-bc20-f8b312245aa4.png)

**Comment by A-L33** [comment]
@brentryanjohnson @weiwang-gsa I think the language might be helpful.  There are some of our disclaimers in there.  I can try and streamline it a bit or we can move it under the search bar.  Thoughts?  If we don't think it's valuable, then we can remove it and close 13 out.

**Comment by weiwang-gsa** [comment]
@A-L33 If you do want to add some text, and want to use this ticket for that purpose, it's perfectly fine,  I don't have any objection. I only suggest to close it if there is no development needed. :)  As for if content or position/design suggestion, I will leave to Ryan.
