### ISSUE TITLE
Content Documentation in Wiki

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#134]
Include content documentation in the program site github repo that links to each page’s markdown file, so it’s easier for product owners to find the pages they want to update.

**Acceptance Criteria:**
- [ ] Write content documentation in the GitHub wiki

**Comment by JessicaMarine1** [comment]
@brentryanjohnson you mentioned you might want to work on this one.

**Comment by A-L33** [comment]
Story updated at grooming.

**Comment by rebekahperillo** [comment]
Moving to DONE!
