### ISSUE TITLE
Implement DAP - Schedule before Code Freeze

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#136]
- [ ] Implement DAP on program website:  https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf

**Comment by mark-meyer** [comment]
@JessicaMarine1 & @rebekahperillo I believe this is already done. I think we included the snippet when we initially setup the site:



![Image](https://github.com/GSA/smartpay-website/assets/7340303/7e8901e6-a0d3-457f-9c5f-abf623fbd1e8)

**Comment by JessicaMarine1** [comment]
Moving to DONE!!

**Comment by rebekahperillo** [comment]
Thanks to you both!

Rebekah Knouse Perillo (she/her)

Lead Business Management Specialist

Center for Charge Card Management
Office of Professional Services and Human Capital Categories
Federal Acquisition Service, U.S. General Services Administration

301-938-5257

***@***.***


Follow the GSA SmartPay program on social media...Tweet with us on Twitter
<https://twitter.com/GSASmartPayNews> and friend us on Facebook
<https://www.facebook.com/GSASmartPayNews/>!
[image: image.png]
