### ISSUE TITLE
State tax | Tax Forms

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#14]
Path: smarttax/state-tax-forms
File name: 
Design: [State Tax Info > State Tax Forms](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38009&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 
**NOTE:** Most of this has already been implemented; may need to re-visit based on updated design.

Links: https://docs.google.com/document/d/14nNOfoL_j-gfv-e0QR8J-ukdnT7J1NDdWAJUR0Xs2Kk/edit

**Comment by JessicaMarine1** [comment]
Question: does the program need to provide a link to each state / territory site or is that something the SD team can scrape from the current site?

**Comment by A-L33** [comment]
Left a comment in story #13 .  Form information is available here:  https://docs.google.com/document/d/14nNOfoL_j-gfv-e0QR8J-ukdnT7J1NDdWAJUR0Xs2Kk/edit

**Comment by brentryanjohnson** [comment]
I'm working with the engineers on a data structure for this that will separate the content from its presentation.

# `{{ state }}` tax information
________________

`True`
	if state has special forms, regulations, or exceptions
`False`
	if state does not have special forms, regulations, or exceptions
	
`If true: class="usa-alert usa-alert--info`"

## State forms or exceptions apply
`{{ state }}` has special forms, regulations, or exceptions.


Example:

![Alert banner with State forms or exceptions apply, Arizona has special forms, regulations, or exceptions](https://user-images.githubusercontent.com/32855580/217960020-82489f6f-1efa-4cce-8987-47f7ef29a126.png)

________________


✅ if exempt
❌ If not exempt
	

✅   Individually billed accounts (IBA) `{{ are/are not }}` exempt from state sales tax.
❌   Centrally billed accounts (CBA) `{{ are/ are not }}`  exempt from state sales tax [a].


[Need help recognizing a card or telling if a card is an IBA or CBA?](https://smartpay.gsa.gov/content/recognizing-your-account)

________________

`if required forms`
## Required forms

`if purchase card forms`
###    Purchase card
* List forms

`if purchase card notes`
Notes

`if travel card forms`
###    Travel card
* List forms

`if travel card notes`
Notes
________________

`if state laws, regulations, policies`
## State laws, regulations, policies
* List policies

`if policies notes`
Notes

________________

## State point of contact
Website
1-xxx-xxx-xxxx


* Updated `{{ date }}`
* 
[a]There may be a third category here...something like "are kinda exempt" 🤷

**Comment by vickimcfadden** [comment]
Replicate the design of GSA.gov with dropdown by state (in alphabetical order): https://www.gsa.gov/travel/plan-book/state-tax-exemption-information-for-government-charge-cards?_ga=2.120424204.586479946.1676399924-1523180152.1676399924#/state/louisiana

Note: no map needed now (for accessibility reasons and for people like vicki who can't find states on a map)

**Comment by JessicaMarine1** [comment]
- Do we want to use the clickable states – where each state has own page/URL (better for analytics and google searches) or the dynamic dropdown where the info populates beneath

- Discussed pros/cons of each

- Mark suggested having the dropdown direct to a standalone page where the dropdown persisted

- Decision: For this sprint, going to go with the dynamic dropdown where the info populates beneath. Will add new story to consider moving to standalone pages

**Comment by A-L33** [comment]
@weiwang-gsa @brentryanjohnson I archived issue #13 to avoid confusion.  I'd like to look into having the disclaimer text under the drop down list.  To avoid confusion, I pulled it out to a separate document for review.  @brentryanjohnson, please take a look and let us know what you think.  https://docs.google.com/document/d/1YtTdedBZkV21SiBBxh2tyhhEYHEruWFaeX47iA6H3f8/edit#

**Comment by weiwang-gsa** [comment]
@A-L33 Just want to confirm, For Colorado the forms are same for travel and purchase, is that correct?


![Image](https://user-images.githubusercontent.com/119954777/221247458-16c16e27-fad7-41d7-9f95-0627a59ee92d.png)

**Comment by A-L33** [comment]
@weiwang-gsa Confirmed.  One is a general purpose transaction form and one specific to credit cards.  But both forms are usable for Purchase and Travel.

**Comment by weiwang-gsa** [comment]
@A-L33 @johnbeallgsa I am not able to get all states info in, there are state difference and I need to adjust code accordingly, the process is slower than what I thought. You can view my current process here: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/wwang-issue14/smarttax/state-tax-information/

Completed:
1. navigation for state tax information
2. state drop down implementation
3. Adjusted code structure to fit state info differences.
4. 20 states data info

To Do:
1. other 36 state data
2. icon for exempt and not exempt 
3. Will talk to Jeff and Ryan regarding some questions I have.

**Comment by A-L33** [comment]
@weiwang-gsa @jfredrickson5 Apologies, we received an update to the information for Hawaii.  Please see below and in the Google Doc:

HAWAII
The state does not have a sales tax, instead it assesses a General Excise Tax (GET) and a Transient Accommodation Tax (TAT) on merchants.
Individually billed accounts (IBA) are not exempt from GET or TAT.
Centrally billed accounts (CBA) may be exempt from GET.
[Need help recognizing a card or telling if a card is an IBA or CBA?](https://smartpay.gsa.gov/content/recognizing-your-account)

Required forms for Purchase:
No required forms identified.

Notes
The State of Hawaii does not assess state sales tax on consumers.  Instead, the state assesses GET on businesses for the sale of goods.  

Notes for the GET:
Businesses have the ability to pass along the GET to cardholders.
If a business sells goods to the federal government, the sale is exempt and the business may claim a deduction.
Should the vendor not claim a deduction, the assessment of GET is allowable as it is not a state sales tax.

State laws, regulations, policies
[Tax Facts 37-1 General Excise Tax](https://tax.hawaii.gov/legal/a2_b2_1taxfacts/)
[An Introduction to the Transient Accommodations Tax](https://files.hawaii.gov/tax/legal/brochures/TAT_brochure.pdf)

State point of contact
[Hawaii Department of Taxation](https://tax.hawaii.gov/)
1-808-587-1577

*Updated 02/15/2023

**Comment by A-L33** [comment]
@weiwang-gsa Thank you!

**Comment by mark-meyer** [comment]
Mockup with dropdown on individual page:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/7340303/221987890-1557ddc8-5e89-4d4f-9c65-55d08d3d55ca.png">

**Comment by jfredrickson5** [comment]
[Here's a direct link to the relevant section for QA](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/state-tax-information/).

**Comment by A-L33** [comment]
@jfredrickson5 @johnbeallgsa Please let us know when you are able to update the language for the drop down.  Thank you!

**Comment by jfredrickson5** [comment]
@A-L33 @johnbeallgsa OK, it's ready!

**Comment by johnbeallgsa** [comment]
@jfredrickson5 @A-L33 Looks great. Moving to done.! Thank you, Jeff!

**Comment by mark-meyer** [comment]
@klohman I think we still have a bit of work on the individual state pages, but this page should be ready for review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/state-tax-forms/

**Comment by rebekahperillo** [comment]
@A-L33 Andrew, are you available to review/approve this story? Thank you!

**Comment by A-L33** [comment]
Done!
