### ISSUE TITLE
Statistics and Reports landing page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#141]
Path: about/statistics
File name: 
Design: [About > Statistics and Reports ](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A40634&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked

**NOTE**: When implementing this page, please make sure that the path in the top nav matches the final URL of the page. They are different right now.
 - page is about/statistics-and-reports
 - nav is about/statistics

_______________ 

Statistics & Reports landing page: https://docs.google.com/document/d/1QCKgQU8Jns3MK0hzN87RUDJXJu1JfC-uF2t4LwFWwsM/edit#.

(obsolete) ~~Purchase Card FPDS Reports: https://docs.google.com/document/d/1W_pfb8TX-gwqC6ju9atkr-ZJoDXrnUJmmULqggZvmPU/edit#heading=h.3d9bgv6pfswu.~~

(obsolete) ~~Sales, Transactions and Account Holder Data: https://docs.google.com/document/d/1qmjMCQ224h_9jHZQGW7DssaxZUG1ym7VRZmtGVfJ9Hc/edit#heading=h.qltmvcy0iy7f.~~

**Comment by JessicaMarine1** [comment]
@brentryanjohnson @A-L33 we will need the summary language for this landing page: https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A37435&t=NB2CPqpZgPZBO4xz-1

**Comment by JessicaMarine1** [comment]
@brentryanjohnson do you want to combine these 3 docs and update path & front matter?

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 ✅ This one should be good to go. I consolidated them all into (what used to be) Program Statistics Overview (#70) and added a note at the top of each.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson what is the preferred URL for this page? Please see discrepancy above in the issue?

**Comment by brentryanjohnson** [comment]
Simplifying to `/statistics/` in #182

**Comment by weiwang-gsa** [comment]
@klohman I think this one also ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/statistics/

**Comment by weiwang-gsa** [comment]
@klohman update the order of content, it is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/statistics/

**Comment by rebekahperillo** [comment]
@klohman I don't see this part in the page:

## Refunds
Agencies and organizations have the opportunity to earn refunds that can directly fund and support mission-critical efforts.
Learn more about refunds

**Comment by klohman** [comment]
@rebekahperillo We created a ["Refunds" page](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/refunds/) separately that includes all of the refund information, so it's no longer nested below Stats & Reports. 

The updated IA/design then removed that blurb from this page since it's a separate menu item.

**Comment by rebekahperillo** [comment]
Thank you, @klohman .

And, where did this content come from? I don't see it on the (linked Google doc - https://docs.google.com/document/d/1QCKgQU8Jns3MK0hzN87RUDJXJu1JfC-uF2t4LwFWwsM/edit#). Just trying to make sure it's all in the right spot. :) 

Thank you!

Refund Reporting
The GSA SmartPay® program generates performance-based refunds for agencies/organizations.
Types of refunds include:
Sales refunds: Based on the dollar or spend volume during a specified time period.

Corrective refunds: Payments made to the agency/organization to correct improper or erroneous payments on an invoice.

[Annual Refund Report (xlsx)](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/files/refund-report.xlsx)

**Comment by klohman** [comment]
@rebekahperillo 

[This is where the Refund Reporting content](https://docs.google.com/document/d/1DiqsJ3naYNnfztsvFlX6P1sKqk_Ro0ZuRfsDtTg9ZwA/edit) originated. Each of the sections on the Stats & Reporting page used to be its own page, so the content was originally spread over a couple google docs. 

It's also been updated in the Figma - not as easy to review, edit as the google docs though. 
![image](https://github.com/GSA/smartpay-website/assets/18366192/c495b360-eaee-4eed-b92b-e47dad8f7b7a)

**Comment by rebekahperillo** [comment]
@klohman One request here if possible. Since refunds were added to the bottom, can we update the language at the top to:

We offer statistics and reporting on spend, transactions, the number of account holders, and refunds.

**Comment by klohman** [comment]
@weiwang-gsa 

Can you update the subtitle to read "We offer statistics and reporting on spend, transactions, the number of account holders, and refunds."

![image](https://github.com/GSA/smartpay-website/assets/18366192/198ace45-48e9-45e8-810b-6f45a6962592)

**Comment by weiwang-gsa** [comment]
@klohman update is merged into main, ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/statistics/

**Comment by klohman** [comment]
@rebekahperillo Ready for your re-review!

**Comment by rebekahperillo** [comment]
Fabulous! Moving to "Done"! Thank you!
