### ISSUE TITLE
Contact landing page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#142]
Path: contact/
File name: 
Design: [Contact](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38522&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________

**Comment by mark-meyer** [comment]
@klohman this is "ready" along with the other contact pages:

Per discussion today, this page is no longer needed. The `contact/` link will go directly to Customer Support.
