### ISSUE TITLE
Individual Audit

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#144]
Path: 
File name: 
Design: [Policies & Audits > Audit Repo > Audit](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A44542&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

Related to #44. When a user selects a specific audit report, this is how it should look.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson what should the path be for each of the individual audit reports?

**Comment by klohman** [comment]
The Individual Audit screens will include a button to "View Full Audit." Some of the audits are linked to PDFs currently on SmartPay site, and some are linked to external URLs (not PDFs). 

@JessicaMarine1 

### Linked to internal PDF
- [ ] [U.S. Department of Housing and Urban Development (HUD), Washington, DC - Government Purchase Cards](https://smartpay.gsa.gov/sites/default/files/2020-KC-0001.pdf)
- [ ] [U.S. Department of Housing and Urban Development (HUD), Washington, DC - Government Travel Cards](https://smartpay.gsa.gov/sites/default/files/2020-KC-0002.pdf)
- [ ] [Controls Over the SEC’s Travel Charge Card Program Could Be Strengthened To More Fully Comply With Requirements and Maximize Benefits](https://www.sec.gov/files/Controls-Over-the-SECs-Travel-Charge-Card-Program-Could-Be-Strengthened-Report-No-560.pdf)
- [ ] [Disaster Response: Agencies Should Assess Contracting Workforce Needs and Purchase Card Fraud Risk](https://smartpay.gsa.gov/sites/default/files/GAO-21-42%20Final%20Report%20dtd%2011-24-2020%2C%20DISASTER%20RESPONSE_%20Agencies%20Should%20Assess%20Contracting%20Workforce%20Needs%20and%20Purchase%20Card%20Fraud%20Risk.pdf)
- [ ] [DoD Should Strengthen Its Ongoing Actions to Reduce Improper Travel Payments](https://smartpay.gsa.gov/sites/default/files/downloads/700931.pdf)
- [ ]  [Audit of GSA’s Fiscal Year 2018 Travel Card Program: Report Number A190030/O/5/F19003](https://smartpay.gsa.gov/sites/default/files/downloads/OIG_Audit_of_GSA%27s_FY2018_Travel_Card_Program%20.pdf)
- [ ] [GSA Office of Inspector General (IG)’s Fiscal Year 2018 Risk Assessment of GSA’s Charge Card Program](https://smartpay.gsa.gov/sites/default/files/downloads/Final_190041_Charge_Card_Risk_Assessment_9-27-19.pdf)
- [ ] [The U.S. Department of the Interior (DOI) Needs to Improve Internal Controls Over the Purchase Card Program](https://smartpay.gsa.gov/sites/default/files/downloads/FinalAudit_PurchaseCardInternalControls_Public_0.pdf)
- [ ] [Fiscal Year 2016 Risk Assessment of the Social Security Administration’s Charge Card Programs](https://smartpay.gsa.gov/sites/default/files/A-13-17-50231.pdf)



### Linked to External sites 
- [ ] [Department of Transportation (DOT) Needs To Enhance Oversight of Its Purchase Card Program To Mitigate Internal Control Weaknesses](https://www.oig.dot.gov/sites/default/files/DOT%20Purchase%20Card%20Program%20Final%20Report%5E03-11-20.pdf)
- [ ] [The National Security Agency (NSA) Audit of the Agency’s Travel Program AU-18-0003](https://www.oversight.gov/report/nsa/audit-agency%E2%80%99s-travel-program)
- [ ] [Audit of the Department of Defense’s (DoD) Management of the Cybersecurity Risks for Government Purchase Card Purchases of Commercial Off-the-Shelf Items DoDIG-2019-106](https://www.dodig.mil/reports.html/Article/1920236/audit-of-the-dods-management-of-the-cybersecurity-risks-for-government-purchase/)
- [ ] [Audit of the Air Force Nonappropriated Fund Government Purchase Card Program DoDIG-2019-113](https://www.dodig.mil/reports.html/Article/1938309/audit-of-the-air-force-nonappropriated-fund-government-purchase-card-program-do/)
- [ ] [Governance: Improving Controls Over the Use of Procurement Cards Could Better Ensure Compliance and Limit Potential Misuse](https://amtrakoig.gov/sites/default/files/reports/OIG-A-2019-013%20Controls%20Over%20PCards.pdf)
- [ ] [2017 Annual Report: Additional Opportunities to Reduce Fragmentation, Overlap, and Duplication and Achieve Other Financial Benefits](https://www.gao.gov/products/GAO-18-371SP)
- [ ] [DoD Reporting of Charge Card Misuse to OMB](https://www.dodig.mil/reports.html/Article/1485315/dod-reporting-of-charge-card-misuse-to-omb/)
- [ ] [Report on the Government Purchase Card Initiative](https://oversight.gov/report/cigie/report-government-purchase-card-initiative)
- [ ] [The Department of State’s Major Management And Performance Challenges](https://www.oversight.gov/report/dos/inspector-general-statement-department-state%E2%80%99s-major-management-and-performance)
- [ ] [Government Purchase Cards: Little Evidence of Potential Fraud Found in Small Purchases, but Documentation Issues Exist](https://www.gao.gov/products/GAO-17-276)
- [ ] [Risk for Environmental Protection Agency’s (EPA) Fiscal Year 2016 Purchase Card and Convenience Check Program Warrants an Audit](https://www.epa.gov/office-inspector-general/report-risk-epas-fiscal-year-2016-purchase-card-and-convenience-check)
- [ ]  [United States Postal Service (USPS) Fleet Specialty Credit Cards - Eastern Area](https://www.uspsoig.gov/reports/audit-reports/fleet-specialty-credit-cards-eastern-area)
- [ ] [Veterans Health Administration (VAMC): Review of Alleged Irregular Use of Purchase Cards by the Engineering Service at the Carl Vinson VA Medical Center in Dublin, Georgia](https://www.oversight.gov/report/va/review-alleged-irregular-use-purchase-cards-vha%E2%80%99s-engineering-service-carl-vinson-va)
- [ ] [Government Purchase Cards: Opportunities Exist to Leverage Buying Power](https://www.gao.gov/products/GAO-16-526)
- [ ] [Federal Travel: Opportunities Exist to Improve Data and Information Sharing](https://www.gao.gov/products/GAO-16-657)
- [ ] [DoD Officials Did Not Take Appropriate Action When Notified of Potential Travel Card Misuse at Casinos and Adult Entertainment Establishments](https://www.dodig.mil/Reports/Compendium-of-Open-Recommendations/Article/1119310/dod-officials-did-not-take-appropriate-action-when-notified-of-potential-travel/)
- [ ] [EPA Oversight of Travel Cards Needs to Improve](https://www.epa.gov/office-inspector-general/report-epa-oversight-travel-cards-needs-improve)
- [ ] [Fiscal Year 2015 Risk Assessment of the Department of Homeland Security (DHS) Bank Card Program Indicates Moderate Risk](https://www.oversight.gov/report/dhs/fiscal-year-2015-risk-assessment-dhs-bank-card-program-indicates-moderate-risk)
- [ ] [Financial Management: Actions Needed to Strengthen GAO's Purchase Card Program Controls](https://www.gao.gov/products/OIG-15-2)
- [ ] [Audit of Engineering Service Purchase Card Practices at the Ralph H. Johnson VA Medical Center, Charleston, South Carolina](https://www.va.gov/oig/pubs/VAOIG-13-02267-124.pdf)

**Comment by brentryanjohnson** [comment]
## Linked to internal PDF
 U.S. Department of Housing and Urban Development (HUD), Washington, DC - Government Purchase Cards
`policies-and-audits/audits/2020-hud-purchase`
 U.S. Department of Housing and Urban Development (HUD), Washington, DC - Government Travel Cards
`policies-and-audits/audits/2020-hud-travel`
 Controls Over the SEC’s Travel Charge Card Program Could Be Strengthened To More Fully Comply With Requirements and Maximize Benefits
`policies-and-audits/audits/2020-sec-travel`
 Disaster Response: Agencies Should Assess Contracting Workforce Needs and Purchase Card Fraud Risk
`policies-and-audits/audits/2020-gao-disaster-response`
 DoD Should Strengthen Its Ongoing Actions to Reduce Improper Travel Payments
`policies-and-audits/audits/2020-gao-dod-travel`
  Audit of GSA’s Fiscal Year 2018 Travel Card Program: Report Number A190030/O/5/F19003
`policies-and-audits/audits/2019-gsa-travel`
 GSA Office of Inspector General (IG)’s Fiscal Year 2018 Risk Assessment of GSA’s Charge Card Program
`policies-and-audits/audits/2019-gsa-travel`
 The U.S. Department of the Interior (DOI) Needs to Improve Internal Controls Over the Purchase Card Program
`policies-and-audits/audits/2019-doi-purchase`
 Fiscal Year 2016 Risk Assessment of the Social Security Administration’s Charge Card Programs
`policies-and-audits/audits/2016-ssa-purchase-travel`
## Linked to External sites
 Department of Transportation (DOT) Needs To Enhance Oversight of Its Purchase Card Program To Mitigate Internal Control Weaknesses
`policies-and-audits/audits/2020-dot-purchase`
 The National Security Agency (NSA) Audit of the Agency’s Travel Program AU-18-0003
`policies-and-audits/audits/2019-nsa-travel`
 Audit of the Department of Defense’s (DoD) Management of the Cybersecurity Risks for Government Purchase Card Purchases of Commercial Off-the-Shelf Items DoDIG-2019-106
`policies-and-audits/audits/2019-dod-purchase`
 Audit of the Air Force Nonappropriated Fund Government Purchase Card Program DoDIG-2019-113
`policies-and-audits/audits/2019-dod-air-force-purchase`
 Governance: Improving Controls Over the Use of Procurement Cards Could Better Ensure Compliance and Limit Potential Misuse
`policies-and-audits/audits/2019-amtrak-purchase`
 2017 Annual Report: Additional Opportunities to Reduce Fragmentation, Overlap, and Duplication and Achieve Other Financial Benefits
`policies-and-audits/audits/2018-gao`
 DoD Reporting of Charge Card Misuse to OMB
`policies-and-audits/audits/2018-dod-purchase-travel`
 Report on the Government Purchase Card Initiative
`policies-and-audits/audits/2018-cig-purchase`
 The Department of State’s Major Management And Performance Challenges
`policies-and-audits/audits/2018-dos`
 Government Purchase Cards: Little Evidence of Potential Fraud Found in Small Purchases, but Documentation Issues Exist
`policies-and-audits/audits/2017-gao-purchase`
 Risk for Environmental Protection Agency’s (EPA) Fiscal Year 2016 Purchase Card and Convenience Check Program Warrants an Audit
`policies-and-audits/audits/2016-epa-purchase`
  United States Postal Service (USPS) Fleet Specialty Credit Cards - Eastern Area
`policies-and-audits/audits/2017-usps-fleet`
 Veterans Health Administration (VAMC): Review of Alleged Irregular Use of Purchase Cards by the Engineering Service at the Carl Vinson VA Medical Center in Dublin, Georgia
`policies-and-audits/audits/2017-va-purchase`
 Government Purchase Cards: Opportunities Exist to Leverage Buying Power
`policies-and-audits/audits/2016-gao-purchase`
 Federal Travel: Opportunities Exist to Improve Data and Information Sharing
`policies-and-audits/audits/2016-gao-travel`
 DoD Officials Did Not Take Appropriate Action When Notified of Potential Travel Card Misuse at Casinos and Adult Entertainment Establishments
`policies-and-audits/audits/2016-dod-travel`
 EPA Oversight of Travel Cards Needs to Improve
`policies-and-audits/audits/2016-epa-travel`
 Fiscal Year 2015 Risk Assessment of the Department of Homeland Security (DHS) Bank Card Program Indicates Moderate Risk
`policies-and-audits/audits/2016-dhs-purchase`
 Financial Management: Actions Needed to Strengthen GAO's Purchase Card Program Controls
`policies-and-audits/audits/2015-gao-purchase`
 Audit of Engineering Service Purchase Card Practices at the Ralph H. Johnson VA Medical Center, Charleston, South Carolina
`policies-and-audits/audits/2014-va-purchase`

**Comment by brentryanjohnson** [comment]
## External

DOI’s Internal Controls For Purchase Cards And Fleet Cards
[`policies-and-audits/audits/2016-doi-purchase-fleet`](https://www.doioig.gov/reports/audit/us-department-interiors-internal-controls-purchase-cards-and-fleet-cards-0)

**Comment by weiwang-gsa** [comment]
@klohman This is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/policies-and-audits/audits/

**Comment by klohman** [comment]
@weiwang-gsa 

- View Full Audit gives 404 error 
    - [Disaster Response: Agencies Should Assess Contracting Workforce Needs and Purchase Card Fraud Risk](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website//files/audits/2020-gao-disaster-response.pdf)

**Comment by weiwang-gsa** [comment]
@klohman code change are made, it is ready for review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/policies-and-audits/audits/2020-gao-disaster-response/

**Comment by klohman** [comment]
@rebekahperillo This one is ready for your review.

**Comment by rebekahperillo** [comment]
@JessicaMarine1  Hi! Any suggestion on how to approve the this story? Thank you!

**Comment by JessicaMarine1** [comment]
@rebekahperillo I think you need to click into each audit (https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/policies-and-audits/audits/) and make sure each one looks as you'd expect.

**Comment by rebekahperillo** [comment]
Ahhh, I've already done that. :) Moving to "DONE"! :) Thank you (I thought I had to verify the path name)!
