### ISSUE TITLE
QASP Compliance

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#147]
As a development team, in order to provide high-quality code to SmartPay, we need to comply with the 18F Quality Assessment Surveillance Plan ([QASP](https://derisking-guide.18f.gov/qasp/)).

**Acceptance Criteria:**
Ensure that the following non-functional requirements are being met:

 

- [ ] Tested code: Minimum of 90% test coverage of all code
- [ ] Properly Styled Code: 0 linting errors and 0 warnings
- [ ] Accessibility: 0 errors reported using an automated scanner (such as Pa11y) -- completed as part of #18; Confirm it is still working with Astro
- [ ] Deployed: Successful build with a single command
- [ ] Security: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities (Clean tests from a static testing SaaS (such as [npm audit](https://docs.npmjs.com/cli/audit)))

**Comment by A-L33** [comment]
@jfredrickson5 @mark-meyer Is there a good way for me to QA this or is it safe for me to accept it since I'm sure it's been through the team's internal process?  Just let me know.  Thank you!

**Comment by jfredrickson5** [comment]
I think it's safe to accept it. We have security scanning in place that can be reviewed here: https://github.com/GSA/smartpay-website/security

And we expanded on the automated tests by adding a broken link checker and a linter (checker for properly styled code). These will run on every change:

![screenshot-20230731-145424](https://github.com/GSA/smartpay-website/assets/19416314/970e4f5b-c78d-4a8f-bbcd-55e4d8b9fd8c)

**Comment by A-L33** [comment]
Done!
