### ISSUE TITLE
State tax | Recognizing Charge Cards

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#15]
Path: smarttax/recognizing-your-account
File name: 
Design: [State Tax Info > Recognizing Charge Cards](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38068&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

**NOTE:** This has already been implemented partially. May need to re-visit based on updated design.

**Acceptance criteria:**

- User has access to information to (https://smartpay.gsa.gov/content/recognizing-your-account) which provides:
   - Identify cards by physical attributes (e.g., card art), BIN prefix, and as applicable 6th digit identifier
   - Determine exemption eligibility status for each type of card (i.e., Purchase, IBA Travel, CBA Travel, Travel Tax Advantage, Fleet, Integrated)

**Comment by weiwang-gsa** [comment]
got Card SVGs images from Ryan: https://drive.google.com/drive/folders/13XvKNKpXd-dDR3g9VyWjSCvmnkXhzzch?usp=sharing

**Comment by brentryanjohnson** [comment]
Suggested edits are in [🔒 this google doc](https://docs.google.com/document/d/1CaTuTofajBDa4ZcNL55fyePU1a1xi7TIFp9YaRF5Zi8/edit?usp=sharing)

**Comment by brentryanjohnson** [comment]
@A-L33 The video on this page isn't captioned and consequently isn't Section 508 compliant. See the note in the ☝ doc in the previous comment.

**Comment by A-L33** [comment]
Let's pull that for now and I'll circle back with Erin.

**Comment by A-L33** [comment]
@brentryanjohnson I talked to Rebekah about the video and all of our videos.  She is reviewing them and will make a list of anything that isn't captioned and will be taking steps.  I don't expect that we'll have the issue addressed for a couple of weeks.  For this video re: Tax Advantage Travel, let's pull it.  I just watched it again and it's basically a commercial.

**Comment by A-L33** [comment]
@brentryanjohnson I have an question for Rebekah about best practices in the document.  Once she answers, we should be in good shape.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson @A-L33 I have following questions:

1. xxx  may have two different designs: this sentence repeated in almost each card type, but some places it is xx cards and some places it is xx count, is it possible to be consistent? e.g. currently I make it same as account title, in code I am using variable for this. (see screenshot Q1)
2. just want to make sure my understanding is correct, we are replacing list item to grid layout, right? (screenshot Q2)
3. is sit digit section current design ok? or you prefer to use table structure with column name and border? (see screenshot Q3)

![Image](https://user-images.githubusercontent.com/119954777/219099192-f0bb16b6-304a-4385-bca5-a2de3d5741e5.png)

**Comment by A-L33** [comment]
@weiwang-gsa This is good to go.  I reviewed the card v. account issue and it all looks right.  @brentryanjohnson We talked about this before and it sounded like you were fine with it.  Let me know if you have any concerns.

**Comment by weiwang-gsa** [comment]
@A-L33 @brentryanjohnson changes I made below:
You can review here: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/wwang-issue15/smarttax/recognizing-your-account/
1. Removed banner hero image
2. Removed best practice sections
3. Removed video
4. Added table implementation for sixth digit section. Currently I keep both implantations there just for comparison. Top one is using grid layout, 2nd is using table layout. @brentryanjohnson, I used default USWDS borderless table. It has underline for each row. I tested to remove that line, it doesn't look very nice. As user scroll up and down, without line, it is hard to tell the text underneath the image belongs to which image. user may also need to scroll up to see column name and tied up with associated value.  Please let me know which implantation you prefer, if you prefer table layout, I will remove the top one.

**Comment by brentryanjohnson** [comment]
The first implementation (grid layout) looks cleaner to me. I think we should go with that one.

**Comment by A-L33** [comment]
Agree with Ryan.

**Comment by A-L33** [comment]
@brentryanjohnson Sorry for the late addition.  As we discussed this afternoon, we thought that adding in the IBA/CBA definitions  from the legal history page to this page would be helpful.  What's the best way to do this Ryan?  Thank you!  Text below:

Centrally billed accounts (CBA): Accounts are issued at the agency, bureau, division, or fleet level, rather than to individuals (even if an individual’s name is on the card). The federal government is billed directly for the purchase of goods and services and should not be assessed sales or use tax. These include:

Purchase cards
CBA Travel cards
Fleet cards
Integrated cards
Tax Advantage Travel cards

Individually billed accounts (IBA): Accounts are issued to authorized federal government employees. Transactions may include travel expenses, which are paid by the employee directly and are later reimbursed by the federal government. This applies to IBA travel cards.

**Comment by brentryanjohnson** [comment]
These definitions are good candidates for content reuse, since I'm certain this isn't the only page for which defining those terms would be helpful to users. But I'm wondering about the role of [the glossary](https://smartpay.gsa.gov/glossary#c) in this, since the role of the glossary is defining terms. I noticed you can't currently link to a specific term in the glossary (just the respective alphabetical section), but do you think we might be able to use the glossary? I don't think we want to define these terms on every single page, as they are on _a lot_ of pages.

**Comment by weiwang-gsa** [comment]
@A-L33 @brentryanjohnson based on feedback, below changes are made:  ( Preview URL:https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/wwang-issue15/smarttax/recognizing-your-account/#section_2)

1. Removed the table layout for sixth section
2. Added top buttons for in-page nav, button click leads to corresponding section header. I also tried side nav combined with in-page nav on my local, but both has the same drawback, it doesn't stay visible when user scroll down. USWDS in-page nav will stay visible as user scroll, it conflicts with its side Nav design. If we use USWDS in-page nav, then we need to redesign current navigation structure. I think this part should be tracked as separate story. I can explain it in parking lot meeting if needed. screen shot below is my local machine. I did not check in code implementation for the right side nav part. 

![Image](https://user-images.githubusercontent.com/119954777/219685964-89306f51-4218-4ede-96cc-45e649d58d8d.png)

**Comment by A-L33** [comment]
@brentryanjohnson Let's chat on Wednesday about how we want to fold in the "IBA/CBA" issue.  Also, there are some style guide things that I found; capitalization of business lines, the trademark sign.  These things may have changed in the style guide recently.

@weiwang-gsa Looks great!  After I talk to Ryan, I'll give you the last set of changes and we should be able to finalize.  Sorry about the last changes and thank you!

**Comment by brentryanjohnson** [comment]
@A-L33 Style guide updates are [in this preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/rj-issue15/smarttax/recognizing-your-account/).

I didn't add the IBA/CBA definitions we talked about. I'd like to get input from @weiwang-gsa on whether or not that should be a separate issue. 👍

**Comment by A-L33** [comment]
@johnbeallgsa Please QA.  If you are ok with it, hold on moving it to "done."  Looks like @brentryanjohnson may have a final technical question for Wei.

**Comment by weiwang-gsa** [comment]
@brentryanjohnson  based on conversation we have yesterday, I believe we decided to have a separate ticket for adding IBA/CBA definitions (tags) as design pattern for FAQs page, if this page also need to use that pattern, we can add this page to the affected pages of that ticket? When we apply IBA/CBA tag changes, we can implement it for both pages at the same time.

**Comment by brentryanjohnson** [comment]
@weiwang-gsa I added a new issue ☝️ #100

**Comment by JessicaMarine1** [comment]
@A-L33 @johnbeallgsa Can you please review (QA) and move to done if OK? We will address the IBA/CBA tags in #100.

**Comment by melchoyce** [comment]
Noticed there's a bunch of unapproved suggestions here: https://docs.google.com/document/d/1CaTuTofajBDa4ZcNL55fyePU1a1xi7TIFp9YaRF5Zi8/edit

Are those ready to go? Want to try mocking up this page.

**Comment by A-L33** [comment]
@melchoyce We're good.  Those were changes made post-style guide implementation.  I just accepted it so the document is clean.  Please proceed.

**Comment by melchoyce** [comment]
Thanks!

**Comment by mark-meyer** [comment]
@klohman I think this is ready for design review. I've edited the headings per our chat, but you might want to double check to make sure they make sense: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/recognizing-your-account/

**Comment by klohman** [comment]
@mark-meyer 

I think the "The Sixth Digit Identifies Billing Type" heading should also be bumped to an H3. I thought that section was related to the one above, but looking closer I think they're separate.

**Comment by JessicaMarine1** [comment]
@klohman this one is ready for re-review. https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/recognizing-your-account/

**Comment by klohman** [comment]
@rebekahperillo Ready for your review

**Comment by rebekahperillo** [comment]
@A-L33 This is your area. Please review. Thank you, Andrew!

**Comment by A-L33** [comment]
Done!
