### ISSUE TITLE
Move main-content id to bypass side nav

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#155]
- Currently, the `main` element and associated `main-content` id encompasses the side nav
- The `Skip to main content` link is present to enable assistive technology users to skip page navigation and jump to the main content, so we should consider allowing users to skip the side navigation as well.

**Comment by brentryanjohnson** [comment]
@mark-meyer LGTM! Keyboard tab initiates `skip` link which bypasses main nav on homepage and man + sidenav on content pages 👍.

**Comment by mark-meyer** [comment]
Thank you @brentryanjohnson!

@A-L33 the work on this ticket should not change anything in the UI. It's just some reorganization of the html to make it a little easier for assistive tech. I recommend, calling it done if Ryan is okay with it.

**Comment by A-L33** [comment]
@brentryanjohnson Are you ok with it?  If so, I will move it to done.  Thank you!

**Comment by brentryanjohnson** [comment]
@A-L33 Ready to move!

**Comment by A-L33** [comment]
Done!
