### ISSUE TITLE
Program Site: Scan for Vunerabilities

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#160]
In effort to mitigate any security issues during the ATO process, we should scan all dependencies for vulnerabilities before the code freeze.

**Acceptance Criteria:**

- [ ] Scan all dependencies for vulnerabilities
- [ ] Remediate all medium & high vulnerabilities

**Comment by mark-meyer** [comment]
I turned on Dependabot for the repo. I'll check back after it has has some time.

**Comment by mark-meyer** [comment]
@rebekahperillo Everything is setup to scan dependency vulnerabilities.

**Comment by rebekahperillo** [comment]
@mark-meyer Thank you, Mark. Is there anything specific for me to test/view, or simply move to "Done"?

**Comment by JessicaMarine1** [comment]
@rebekahperillo you can view the vulnerability scan here: https://github.com/GSA/smartpay-website/security/dependabot

No issues, so you can move it done :)

**Comment by rebekahperillo** [comment]
Looks good, thank you! Moving to "Done"!
