### ISSUE TITLE
889: Scan for Vunerabilities

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#161]
In effort to mitigate any security issues during the ATO process, we should scan all dependencies for vulnerabilities before the code freeze.

**Acceptance Criteria:**

- [ ] Scan all dependencies for vulnerabilities
- [ ] Remediate all medium & high vulnerabilities

**Comment by mark-meyer** [comment]
@JessicaMarine1 and @rebekahperillo I have updated the dependencies to update the vulnerabilities reported by Dependabot. The easiest way to verify this is to look at the Dependabot alerts here in GitHub: https://github.com/GSA/889-tool/security/dependabot

You should see a screen that show no alerts. [You can also click "7 closed" link which will show you what specifically has been done]


![Image](https://github.com/GSA/smartpay-website/assets/7340303/69324444-1b11-47c0-a71b-ad61681fbb69)

**Comment by rebekahperillo** [comment]
@mark-meyer Hey Mark! I click the link and get a 404 error. Am I doing something wrong here?

**Comment by rebekahperillo** [comment]
@mark-meyer It's back up and working now - no more 404 error! Moving to done, thank you! :)

**Comment by mark-meyer** [comment]
@rebekahperillo Great! I just added as an admin on that GitHub repo.
