### ISSUE TITLE
Tax Resources

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#17]
Path: smarttax/resources
File name: 
Design: [State Tax Info > Tax Resources](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A43370&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked
_______________ 

- Tax Resources: https://docs.google.com/document/d/1C05FtppKTAxGODZnKctTnO-Hz3h4XrHVKTRXTDxxA-k/edit#.

**Comment by JessicaMarine1** [comment]
From a design perspective, where should this link live?

**Comment by weiwang-gsa** [comment]
Q: 
Where we should put this vendor brochure link? Does it exist in current website? if yes, how to navigate to it. Do you want to keep current navigation/page or does it need redesign work?

**Comment by A-L33** [comment]
Let's have a discussion with Ryan for design here.  Right now it's a stand alone page with not a lot of context.

**Comment by weiwang-gsa** [comment]
Current page/Navigation :

![Image](https://user-images.githubusercontent.com/119954777/219131267-354578ed-5e5f-4531-b6ab-f3d1d19d4fba.png)

**Comment by A-L33** [comment]
Make it reusable repeatable for:
- SmartTax
- Publications
- Merchants

Taxonomy?  Side nav?

**Comment by vickimcfadden** [comment]
1. Need a PDF naming convention (get rid of all the %%)
2. Decision: make own page within Tax so it can be reusable later (i.e. under merchants)
3. Tags `Merchant` `SmartTax` `Guide`
4. Replicate content directly from existing website

**Comment by A-L33** [comment]
@brentryanjohnson 
Side nav for SmartTax
Linked to Businesses and Merchants
Landing page for SmartTax?

**Comment by A-L33** [comment]
Tabled until tax sprint finished.

**Comment by JessicaMarine1** [comment]
Need a landing page for the merchant brochure (#17) and tax video (#26). Andrew to create content template that houses both.

**Comment by A-L33** [comment]
@johnbeallgsa @brentryanjohnson Created the landing page and archived issue 26.  Please let me know if you have any questions.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson It didn't look like you had reviewed this content yet, so I changed the tag and moved back to `Backlog (not ready)` until you can confirm.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa
✅ Reviewed

**Comment by mark-meyer** [comment]
@klohman This should be ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/resources/

**Comment by rebekahperillo** [comment]
@A-L33 Andrew, are you available to review/approve this story? Thank you!

**Comment by A-L33** [comment]
Done!
