### ISSUE TITLE
Add line to layout(s) that pulls in and styles intro

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#170]
- Figma designs have a custom-styled "intro" paragraph that cannot easily be added in markdown
- #169 adds a relevant `intro` front matter key (to pages we've already merged) for the purpose of styling this intro paragraph
- This issue is for styling and adding this intro to relevant layouts

**Comment by JessicaMarine1** [comment]
Done per @brentryanjohnson
