### ISSUE TITLE
Usability testing

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#175]
Now that we've built what we think is MVP for the program site, let's test with users!

**Acceptance Criteria:**

- [x] Recruit users
- [x] Develop testing script [(Draft Test Plan)](https://docs.google.com/document/d/1ZV_Lv0c5LLFekoD_W1wlOaeRKqDzxhherTDV2gOSxw0/edit?usp=sharing)
- [x] Conduct usability testing
- [x] Present [findings/recommendations](https://docs.google.com/presentation/d/1_teFJOGYaOJHL2oyQokujI0_iHPoPFv4WeoZAIMc1p0/edit?usp=sharing)
- [x] Backlog changes (MVP v. post-MVP)

**Comment by JessicaMarine1** [comment]
Potential users to test with: https://docs.google.com/spreadsheets/d/1fhsn_ENiYC-4iy-ccXKAwHg7YqhWiLjBGtszpmaTjag/edit#gid=825012245

**Comment by klohman** [comment]
@rebekahperillo 
- Is there any concern with a participant being a contractor/consultant vs. a federal employee? I received a response from a contractor on behalf of my original recruit and just wanted to confirm there is no issue with that.
- I noticed a new tab in the Contact List for program staff - is this good to go?

**Comment by klohman** [comment]
@rebekahperillo I'd like to get your feedback on the test script and tasks in the [SmartPay Program Site Usability Test plan](https://docs.google.com/document/d/1ZV_Lv0c5LLFekoD_W1wlOaeRKqDzxhherTDV2gOSxw0/edit?usp=sharing). Please take a look when you can and feel free to comment or reach out to discuss.

**Comment by rebekahperillo** [comment]
Hi! Just took a quick look. If you need more/different information, please
let me know. Thank you! :)

Rebekah Knouse Perillo (she/her)

Lead Business Management Specialist

Center for Charge Card Management
Office of Professional Services and Human Capital Categories
Federal Acquisition Service, U.S. General Services Administration

301-938-5257

***@***.***


Follow the GSA SmartPay program on social media...Tweet with us on Twitter
<https://twitter.com/GSASmartPayNews> and friend us on Facebook
<https://www.facebook.com/GSASmartPayNews/>!
[image: image.png]

**Comment by klohman** [comment]
@A-L33 @rebekahperillo 

We are still doing a bit more research around the previously mentioned PDF accessibility issue, but I want to share the findings and recommendation from this research-  [SmartPay Website Usability Testing Results - Aug 2023](https://docs.google.com/presentation/d/1_teFJOGYaOJHL2oyQokujI0_iHPoPFv4WeoZAIMc1p0/edit?usp=sharing). 

I'll work with @JessicaMarine1 to get a time set up to more formally present these results, but figured you could get your eyes on  them now in case you want to create and prioritize any stories.

**Comment by rebekahperillo** [comment]
@klohman Thank you! I just requested access to take a look at the doc. I'm in on Friday if you want to chat. Otherwise, I'll be back on August 22.

**Comment by A-L33** [comment]
Done!  Created the following issues and will prioritize with @rebekahperillo 

- #286 
- #287 
- #288 
- #289 
- #290 
- #291
