### ISSUE TITLE
Update external link icon to only non-GSA.gov sites

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#187]
When we originally implemented the site, we were including the external link icon for any non-smartpay.gsa.gov site; this icon should only apply if we're linking to outside of gsa.gov

- [ ] Update external link icon to only non-GSA.gov sites

**Comment by JessicaMarine1** [comment]
@weiwang-gsa GSA.gov doesn't treat it as an external link, so I guess we shouldn't either. Internal.

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/

**Comment by klohman** [comment]
@rebekahperillo Ready for review!

**Comment by rebekahperillo** [comment]
@klohman What's the best way to check this? All looks good on the homepage, but what about the other pages? Suggestions?

**Comment by JessicaMarine1** [comment]
@rebekahperillo these used a script, so you can have confidence that it removed the external link from all the gsa.gov links. I did click around the site and it seemed to be accurate. gsa.gov links now don't have the external link icon (see https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/benefits/) but non-gsa.gov links do (see https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/smarttax/legal-history/). I think you are good to move this to done :)

**Comment by rebekahperillo** [comment]
Sounds good to me! Moving it over to "Done". Thank you! :)
