### ISSUE TITLE
Pre-launch content clean-up

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#19]
Content updates that Andrew/Rebekah/Lora will use to learn how to do content updates:

**Content specific:**
- [x] https://docs.google.com/document/d/1FvR3hje3er5TAWan5nHoD9jZBP2tc6bjT8Ye2cWfQWI/edit

**Comment by rebekahperillo** [comment]
@vickimcfadden Hi! Would you like to add comments here also? I've formatted the doc and included the feedback that you provided last week.

Here's the running list:
https://docs.google.com/document/d/1FvR3hje3er5TAWan5nHoD9jZBP2tc6bjT8Ye2cWfQWI/edit

**Comment by JessicaMarine1** [comment]
Closing #218 as duplicative.

**Comment by JessicaMarine1** [comment]
9/11/2023: All pre-launch content updates have been completed (or will be completed on Wed. by Lora). The only remaining items are post-MVP or need Rebekah's further input. Closing this issue and keeping _new_ running list open in #325
