### ISSUE TITLE
Make Homepage Images Clickable

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#190]
As a user, when I click on images on the homepage, I would like them to link to content.

SPECIFY IMAGES and LINKS

**Comment by weiwang-gsa** [comment]
@klohman does this refer to call out section only? ( 889 tool, statetax and go to events). or this also include the business line section ( those card images), if it include card images, what those images should link to?

**Comment by klohman** [comment]
@weiwang-gsa 
It should apply to all of the homepage images: 
- 889 image = https://889.smartpay.gsa.gov/#/
- Map image = /state-tax-forms/
- Forum image = /events/

For the card images, can we link to /about/business-lines/, but to the corresponding H2 (card title) like we do for links to specific FAQ sections?

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by A-L33** [comment]
Done!
