### ISSUE TITLE
Content | style guide

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#21]
> As a GSA SmartPay content manager, I need guidance on content style to make sure content is consistent across the website. Should we use title case or sentence case? Should we capitalize the word "state" or leave it lower case? Should we punctuate bulleted list items or not?

- Consider adopting an existing style guide (e.g. [GSA](https://insite.gsa.gov/employee-resources/communications/digital-website-communication/content-and-style-guidance-for-gsa-sites), [18F](https://content-guide.18f.gov/))
- Supplement the guide with terms specific to GSA SmartPay (or missing from the adopted guide)

SmartPay draft guide: https://docs.google.com/document/d/19GcaMMf41BdbR5lvZ27c-EHFtAajIdL9qEMtRO0OErY/edit

**Comment by JessicaMarine1** [comment]
Possible inclusion: when linking to external sites; we have a preference for .gov (Example: linking cases in legal history to archives.gov versus justica.com)

**Comment by JessicaMarine1** [comment]
Question(s) to consider:
1. Does the current SmartPay content need to be updated on smartpay.gsa.gov to new syling OR will any changes be done as the content is ported over to the new site?
