### ISSUE TITLE
Ensure all work is mobile-friendly and compatible with modern browsers

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#22]
As a user of the GSA SmartPay website, I need it to be mobile-friendly and compatible with modern browsers so that I can access the site anywhere.

note: this story is to ensure manual testing of functionality

**Acceptance Criteria:**

- [ ] All work completed to-date is mobile-friendly
- [ ] All work completed to-date is compatible with modern browsers

**Comment by JessicaMarine1** [comment]
@A-L33 @johnbeallgsa This ticket was intended to remind you to review all the stories for mobile / browser compatibility. Since you're doing that at the individual story level, is this story unnecessary?

**Comment by A-L33** [comment]
@JessicaMarine1 Archived!
