### ISSUE TITLE
State tax info. on GSA.gov

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#23]
- [ ] Provide new [URL](https://smartpay.gsa.gov/smarttax/state-tax-forms/) to state taxes to Patrick Son in OSC upon launch

-------------

**HISTORY:**

Per Ryan 2/1: We're almost certainly going to break [gsa.gov](http://gsa.gov/)'s scraping of the tax content, and we'll probably need to work with their team to make sure it's functioning when we go live.

SmartPay points of contact:
Sarah Bryant - ZOD <sarah.bryant@gsa.gov>,
Tokey Bradfield - ZOD <tokey.bradfield@gsa.gov>,
Patrick Son - ZOD <patrick.son@gsa.gov>

**June 2023 update**: the scraping got broken during the Drupal 9 update; GSA.gov is now just linking directly to the SmartPay website. If this is the pattern moving forward, we can just provide the updated URL on the new site.

**Comment by JessicaMarine1** [comment]
Sept. 11 - Andrew emailed Patrick with update
Sept. 12 - Patrick acknowledged upcoming change and asked for new re-direct URL when we go live.

**Comment by A-L33** [comment]
Reached out to Patrick Sohn on 10/5.  Waiting for confirmation.

**Comment by JessicaMarine1** [comment]
@A-L33 this is ready for re-review. Patrick has made the changes on GSA.gov and the new redirect from /content/state-tax-information --> smarttax/state-tax-forms seems to have fixed the google issue.

**Comment by A-L33** [comment]
Good to go!
