### ISSUE TITLE
Adding Emergency FAQs to FAQ Page

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#242]
As a user, I would like access to FAQs about emergency use. 

Acceptance Criteria:
- Add "Emergency Use" section to FAQs page.
- Nest "Purchase" and "Fleet" related questions under "Emergency Use".
- Add attached Q&A content (https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/files/publications/publications-emergency-card-use-faqs.pdf).

**Comment by rebekahperillo** [comment]
@weiwang-gsa @brentryanjohnson @klohman How does this look?

**Comment by klohman** [comment]
@rebekahperillo We'll want to add that we want to link to the Emergency FAQ from the All Business Line Publication page (so we don't forget)

**Comment by rebekahperillo** [comment]
@klohman Thank you. I've added it here and I'll add it on the All Business Line issue page.

**Comment by weiwang-gsa** [comment]
@klohman Please let me know if below assumption is correct.

- I put Emergency Use after government shutdown


![Image](https://github.com/GSA/smartpay-website/assets/119954777/5e5b1696-503d-403d-969e-f752bbe1665f)



-  I update the text here (and link it to FAQ Emergency Use section)

Original text:


![Image](https://github.com/GSA/smartpay-website/assets/119954777/2f66a0ef-e76a-44c0-8f9c-e44d4a371187)

New: 

![Image](https://github.com/GSA/smartpay-website/assets/119954777/895d5c1a-53ea-4ce8-bf78-6f5f70d8c8f0)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review, please note since we are at the code freeze phase, everything is merged into staging branch instead of main: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/faq/

**Comment by klohman** [comment]
@weiwang-gsa 

One comment under  "Is there is anything in the SmartPay regulations that stipulate that delivery must be made to a Federal address? Or would it be acceptable for a Federal employee using a valid purchase card
to order supplies for delivery to their private residence? This would be in support of their official
duties in light of the indefinite telework situation." 

- Each "ability to" statement should be bulleted as in the PDF 
![Screen Shot 2023-07-26 at 1 42 19 PM](https://github.com/GSA/smartpay-website/assets/18366192/ebb9dd7a-1338-4653-8b39-5da8cb2c0287)

**Comment by weiwang-gsa** [comment]
@brentryanjohnson , do you think I can safely remove the ", and" from the original PDF document? 


![Image](https://github.com/GSA/smartpay-website/assets/119954777/68c88f85-79d2-474a-ab35-9c0e3ac8fedb)

**Comment by A-L33** [comment]
@brentryanjohnson Grammatically, it is probably not wrong, but it doesn't look great.  I'll defer to your experience Ryan.

**Comment by brentryanjohnson** [comment]
@weiwang-gsa 

- The ",and" can go away, since the bulleted items are not all inclusive.
- The ",or" should remain, since it is important to understanding that it is either or, not both.

As you noted, according to the style guide, the first word of each list item should be capitalized, and each list item should be punctuated with a period. That won't work for the "or", though, so no period on that one.

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for review

**Comment by A-L33** [comment]
Done!

**Comment by rebekahperillo** [comment]
@klohman @A-L33 Forgive me - I don't see the Emergency FAQs on the FAQ page here:

https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/faq/

What am I missing?

**Comment by klohman** [comment]
@rebekahperillo 

The updates are on in staging now (due to code freeze) - here's the link:
https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/faq/

**Comment by rebekahperillo** [comment]
@klohman yessss! thank you!
