### ISSUE TITLE
Add Code Comments to source code

### ISSUE THREAD

**Issue by weiwang-gsa** [GSA/smartpay-website#249]
As developer, I want to add code comments to the source code wherever it needs more explanation to improve code readability, maintainability and collaboration. 

Acceptance Criteria:

- [ ] Develop of consensus among team on documentation style and conventions
- [ ] The code comments should be concise, clear and relevant to the code they annotate
- [ ] The code comments should help other developers understand the purpose, logic and usage of code functionality
- [ ] The code comments should not state the obvious, but rather provide insights not immediately evident from the code itself.

**Comment by weiwang-gsa** [comment]
08/03/2023: Added code comment for components and pages I worked on that need comments.

**Comment by weiwang-gsa** [comment]
@mark-meyer not sure if you need to add code comments as well, if yes, please assign yourself to this ticket, and once you are done with your updates, we can move it to next status. If not, I will move it ready for QA, thanks!

**Comment by A-L33** [comment]
Done!
