### ISSUE TITLE
Add meta description and social media meta tags for SEO

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#250]
## Site lacks a `meta` description for SEO

- Lighthouse audit revealed we're missing `meta` description for search
- Some content pages include `description` key in front matter (for the purpose of `meta` tag), but many lack this key

## Site lacks social media `meta` tags

- The site lacks Open Graph `meta tags` for social media display

```
<meta property="og:title" content="" />
<meta property="og:type" content="" />
<meta property="og:url" content="" />
<meta property="og:image" content="" />
```

- The site lacks social-media-specific `meta` tags

**Comment by mark-meyer** [comment]
@brentryanjohnson I can work on this. Do you have any suggestion for what we should use for `og:image`. [Guidance from Facebook](https://developers.facebook.com/docs/sharing/webmasters/images/) suggests a very specific 1.91:1 aspect ratio. We could probably make the SmartPay logo work there if we don't have a better idea.

For `og:type` are you happy with `<meta property="og:type" content="website" />` or do you have some other schema/taxonomy in mind?

**Comment by brentryanjohnson** [comment]
@mark-meyer I think we should use a cropped version of the hero for `og:image` (even if it is stock). It communicates more about what the site content is about than does the logo.

As for `type`, maybe we can omit that one for now. The schema wants more specificity than we're able to furnish right now.

We'll need to go back in and add `description` to those content pages that don't have it. It looks like most, if not all, of the pages added while I was away lack that front matter key.
