### ISSUE TITLE
GSA favicon

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#251]
- [ ] Implement GSA favicon

**Comment by klohman** [comment]
Preview shared by @jfredrickson5 
https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/jf/fix-favicon-path/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by A-L33** [comment]
Done!
