### ISSUE TITLE
Accessibility error: Policies

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA/smartpay-website#255]
Policies is throwing an accessibility error

`
List items (<li>) are not contained within <ul>, <ol> or <menu> parent elements.`

**Comment by weiwang-gsa** [comment]
@brentryanjohnson this is ready for review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/policies-and-audits/policies/

**Comment by brentryanjohnson** [comment]
✅ This page now scores 100% for accessibility in Lighthouse ✅ 

![screenshot of Lighthouse accessibility audit showing a 100 percent score in green](https://github.com/GSA/smartpay-website/assets/32855580/e8be9ac2-422b-4b13-88dc-f8ad25356a0f)

**Comment by weiwang-gsa** [comment]
@A-L33 @rebekahperillo it passed Ryan's review, ready for QA review now: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/policies-and-audits/policies/

**Comment by A-L33** [comment]
Done!
