### ISSUE TITLE
Tax Video

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#26]
As a user, I want easily digestible information about taxes, so I can consume information by watching a video, instead of reading.

Acceptance criteria:
- User has access to video posted on GSA's YouTube channel at:  [https://www.youtube.com/watch?v=rT3vImFv4-I&t=5s](url)

**Comment by JessicaMarine1** [comment]
- From a design perspective, where should this video be posted / linked on the site?
- Is it better to post a link or embed the video?

**Comment by A-L33** [comment]
@brentryanjohnson Looks like this video might not be subtitled either.  When I looked on youtube, it was but it's not when I play it off our website.  Can you confirm for me?

**Comment by brentryanjohnson** [comment]
It looks like this one does have captions. When embedding on the website, there's a parameter that will autoplay the captions that should be included so that it's clear there are captions. `cc_load_policy=1`

**Comment by A-L33** [comment]
If we think the video conforms, we might be good to go here.

**Comment by A-L33** [comment]
Tabled until tax sprint finished.

**Comment by JessicaMarine1** [comment]
Need a landing page for the merchant brochure (#17) and tax video (#26). Andrew to create content template that houses both.

**Comment by A-L33** [comment]
Based on grooming, this issue is closed.
