### ISSUE TITLE
Incorrectly sized logo at certain screen widths

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/smartpay-website#273]
When the browser window is 769px to 1023px wide, the logo isn't scaled down properly.

![screenshot-20230807-102335](https://github.com/GSA/smartpay-website/assets/19416314/9d0f273b-b46a-42ea-a2d5-2a43a8e923a2)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://demo.smartpay.gsa.gov/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA.

**Comment by weiwang-gsa** [comment]
Please note  https://demo.smartpay.gsa.gov/ is preview link for QA. latest code of staging branch is linked to demo.smartpay.gsa.gov now. (this is part of changes needed for the search.gov set up), the old staging preview link doesn't reflect the latest code change.

**Comment by rebekahperillo** [comment]
@weiwang-gsa Looks great, thank you! Moving to DONE!
