### ISSUE TITLE
889 Tool Language Update (Red triangle icon)

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#278]
As a user, I'd like to see clearer, more succinct language on the 889 tool for results that involve a contractor that provides prohibited equipment (and a red triangle icon is displayed).

Acceptance Criteria:

Change the language for the red triangle icon from: 
"The contractor has represented in SAM that it does provide and/or does use covered (i.e., prohibited) telecommunication equipment. Please follow applicable agency procedures." 

to 

"This contractor has indicated in SAM.gov that it provides or uses prohibited equipment. Please follow your agency's procedures."

**Comment by brentryanjohnson** [comment]
There are comments related to this issue in [#270](https://github.com/GSA/smartpay-website/issues/270#issuecomment-1664256352).

**Comment by mark-meyer** [comment]
@brentryanjohnson this should now have the simpler text! 

https://federalist-adaef58d-ff3c-4a0f-961c-c9916e7bff41.sites.pages.cloud.gov/preview/gsa/889-tool/staging/#/

**Comment by rebekahperillo** [comment]
@mark-meyer Hey Mark! I'm hovering over the symbols, but don't see the text. User error again? :)

**Comment by JessicaMarine1** [comment]
@rebekahperillo It takes a few seconds for the hover-over text to appear.

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo this is ready for review: https://federalist-adaef58d-ff3c-4a0f-961c-c9916e7bff41.sites.pages.cloud.gov/preview/gsa/889-tool/staging/#/

**Comment by A-L33** [comment]
Done!
