### ISSUE TITLE
(HOLD) Pen Test Report: Moderate Finding re: Weak Ciphers

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#281]
Pen Test Report: https://drive.google.com/file/d/1_1Ax2Ki3vuKc0FaOz9A3Tu6lmjyVnEBk/view

- [ ] Remediate Moderate Finding re: Weak Ciphers (pages 4-5 of report)
- [ ] Submit [GSA Penetration Test Remediation and Validation Request](https://docs.google.com/forms/d/e/1FAIpQLSdwYIiaGKN_2IBNLSeaM4EEmYEappERJ639-BbwTix_A6_TUQ/viewform)

**Comment by A-L33** [comment]
@JessicaMarine1 and @A-L33 talked to Tri this morning, he is checking with Arpan.

**Comment by JessicaMarine1** [comment]
Closing this issue; if additional work is needed it will be documented in the POAM.
