### ISSUE TITLE
(HOLD) Pen Test Report: Low Finding re: TLS/DTLS ‘Lucky 13’ vulnerability

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#282]
Pen Test Report: https://drive.google.com/file/d/1_1Ax2Ki3vuKc0FaOz9A3Tu6lmjyVnEBk/view

- [ ] Remediate Low Finding re: TLS/DTLS ‘Lucky 13’ vulnerability (page 6 of report)
- [ ] Submit [GSA Penetration Test Remediation and Validation Request](https://docs.google.com/forms/d/e/1FAIpQLSdwYIiaGKN_2IBNLSeaM4EEmYEappERJ639-BbwTix_A6_TUQ/viewform)

**Comment by A-L33** [comment]
This could be a false positive.  Inherited from cloud.gov.  This could share solution with #281 .

**Comment by JessicaMarine1** [comment]
Closing this issue; if additional work is needed it will be documented in the POAM.
