### ISSUE TITLE
Bookmarks | Post-Launch check

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#292]
Check to make sure work for bookmarks in #84 works.

**Comment by rebekahperillo** [comment]
Check completed using this [spreadsheet](https://docs.google.com/spreadsheets/d/1ZNVAjsy96CtDvHnMkjre0ESKpcOjy_hRmAP49x7-dVQ/edit#gid=892211863). Bookmarks work expect for a few.

Those redirects that need to be corrected are as follows:

<google-sheets-html-origin><style type="text/css"></style>

Previous Link | Redirect
-- | --
http://smartpay.gsa.gov/2023-gsa-smartpay-training-forum | /resources/events/#gsa-smartpay-training-forum
http://smartpay.gsa.gov/forum | /resources/events/#gsa-smartpay-training-forum
http://smartpay.gsa.gov/2023-gsa-smartpay-training-forum-presentations-virtual-forum | /resources/events/#gsa-smartpay-training-forum


In addition, the following should be added per user feedback:
<google-sheets-html-origin><style type="text/css"></style>

Previous Link | Redirect
-- | --
https://smartpay.gsa.gov/content/state-tax-information | /smarttax/state-tax-forms

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 and @mark-meyer I can work on this and send up a PR for review. 👍

**Comment by JessicaMarine1** [comment]
@rebekahperillo this is ready for re-review!

**Comment by rebekahperillo** [comment]
Looks great, moving to DONE! Thank you!
