### ISSUE TITLE
Final QA of site (Vicki)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#293]
Before we go live, we should have someone navigate the site and review content with fresh eyes. Vicki volunteered to do this.

- [x] Review [site](https://demo.smartpay.gsa.gov/) 
- [x] Compare design to ([Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374-35583&mode=design&t=r5lNjd2h4xkepZ34-0))
- [x] Search for Smartpay to ensure P is capitalized everywhere
- [x] Make sure "GSA" precedes _every_ reference to SmartPay
- [x] Ensure that the (R) mark is only used on the first reference on each page / document
- [x] Ensure that all hyperlinks route to the _correct_ place:
   - [x] External (outside of GSA) should have the external icon
   - [x] Make sure links are to _new_ SP sites (not to current one)
- [ ] ~~In the state forms, search for "State of ..." and uncapitalize "State"~~ see #323 

- [x] Log any issues found [here](https://docs.google.com/document/d/1FvR3hje3er5TAWan5nHoD9jZBP2tc6bjT8Ye2cWfQWI/edit)

**Comment by vickimcfadden** [comment]
For comparison to the figma file (I assume this was discussed and agreed to change, but just noting):
- Drop-down under "Stakeholder" - Program Coordinator now vs A/OPC in the figma rendering

**Comment by vickimcfadden** [comment]
@JessicaMarine1 I'm not sure what this is referring to  `In the state forms, search for "State of ..." and uncapitalize "State"`

Otherwise, done. I also did a mobile review.

**Comment by JessicaMarine1** [comment]
@A-L33 or @rebekahperillo so you happen to recall what issue we were trying to solve with this AC:

-[] In the state forms, search for "State of ..." and uncapitalize "State"

**Comment by JessicaMarine1** [comment]
> Otherwise, done. I also did a mobile review.

Thank you @vickimcfadden for such a fast and thorough review!!

**Comment by A-L33** [comment]
The acceptance criteria was to conform to the SmartPay style guide.  I just opened a new ticket #323 to address that specifically, this should be good to go.

**Comment by JessicaMarine1** [comment]
Moving this to done!
