### ISSUE TITLE
Show file type and size for links to non-HTML content.

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#304]
To comply with [USWDS ](https://designsystem.digital.gov/components/link/)guidance, we need to:
**Show file type and size for links to non-HTML content.** 

When possible, create HTML pages instead of linking to files like PDFs. If you do link to a file, tell users ahead of time if the link may trigger a file download, and show the size and format of that file.

We recommend including this information at the end of the link, in the format [FILE_TYPE, SIZE]. We recommend using the file type rather than a product name. Use uppercase for the file type and a comma for the separator. For file size, use the number of pages in the document or the size in MB or KB if the document is not paginated.

_Example 1:_

> GSA published a report, [Transforming the American Digital Experience [PDF, 18 pages]](https://designsystem.digital.gov/files/next/Transforming-the-American-digital-experience.pdf)

_Example 2:_

> Download the [Revised 508 Standards Applicability Checklist [DOCX, 2 pages]](https://assets.section508.gov/files/508-standards-applicability-checklist.docx)

_Example 3:_

> Download the [USWDS 2.11.2 Design Kit for Sketch [ZIP, 13.3 MB]](https://github.com/uswds/uswds-for-designers/releases/download/v2.4.0/uswds-for-designers-v2.4.0.zip)

**Comment by weiwang-gsa** [comment]
which way we are using, total pages or file size?

**Comment by JessicaMarine1** [comment]
I would say page count if we have one.

> For file size, use the number of pages in the document or the size in MB or KB if the document is not paginated.

**Comment by mark-meyer** [comment]
I was able to write an Astro component that does this automatically for local PDFs (those we are hosting) when we build the site. This might be preferable to manually entering the size when the content is added. 

However, there are places on the site where we link to external PDFs like OMB Memoranda, this will be problematic to automate because we would need to download these files every time we build a version of the site.  In those cases it probably makes more sense to do this manually. This makes me think it might be easier to do them all manually so it's not confusing, but this will be some up-front work to go through all the doc.

**Comment by weiwang-gsa** [comment]
@JessicaMarine1  just double check if  the update also include the link button? e.g. change "View Full Audit" to "View Full Audit [PDF, 22 pages]"?



![Image](https://github.com/GSA/smartpay-website/assets/119954777/ddab8a56-5228-44a3-8bed-3b027312b2b5)

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I don't know. USWDS provided guidance for links; I'm not sure if the same applies to buttons.

Adding our designers @actuallyjenn @klohman to see if they know what USWDS would recommend here.

**Comment by klohman** [comment]
> @weiwang-gsa I don't know. USWDS provided guidance for links; I'm not sure if the same applies to buttons.
> 
> Adding our designers @actuallyjenn @klohman to see if they know what USWDS would recommend here.

There isn't the same guidance for buttons, but we'll run into the same screen-reader issue with the button as with the link (i.e., not realizing it has opened a PDF viewer). 

I'm thinking we use a link here instead of a button - and use text "View full audit [PDF, 22 pages]"?

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 @klohman another question, for all business line under publications, is type column still needed if we add [PDF, x pages] in title? 

![Image](https://github.com/GSA/smartpay-website/assets/119954777/79554640-278b-4483-8f16-e7a32b082e0c)

**Comment by JessicaMarine1** [comment]
@weiwang-gsa i think that column becomes redundant and could be deleted. @brentryanjohnson thoughts?

**Comment by brentryanjohnson** [comment]
If we're labeling all non-HTML documents (including Word and Excel), I think we can get rid of the column.

**Comment by klohman** [comment]
@weiwang-gsa 
I thinking moving the "Online Flipbook" to the title column makes sense. It should remain in the same row. 

For the audit - we can keep the current link styling. One note, the text should be sentence case so it should read "View full audit [PDF, 26 pages]"

**Comment by weiwang-gsa** [comment]
@klohman  "View Full Audit" is the original text there, I think Ryan worked on those audits files previously, I have a feeling it followed smartpay style guide, just double check with @brentryanjohnson if I should make it "View full audit [PDF, 26 pages]"

**Comment by brentryanjohnson** [comment]
@weiwang-gsa @klohman Let's use sentence case for the link buttons, as Kristen mentioned. Title case in the style guide is specifically used for headings. I should have used sentence case for the audit links!

**Comment by weiwang-gsa** [comment]
@rebekahperillo the excel file is this one: https://demo.smartpay.gsa.gov/files/ao-approval-tracking-log.xlsx
, not sure if you still want to double check and remove the empty tab/sheets for it, per discussion, we will not use [XLSX, 1 sheet] but use [XLSX, 10 KB] for it.

**Comment by rebekahperillo** [comment]
@weiwang-gsa Looks like there were two empty sheets. Here's the new file with one sheet. If you have any questions, please let me know. Thank you!

[ao-approval-tracking-log.xlsx](https://github.com/GSA/smartpay-website/files/12480970/ao-approval-tracking-log.xlsx)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://demo.smartpay.gsa.gov/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa @klohman I took a look at this too because...it's a lot. 

- [ ] Do we need to add the file size to the xlsx links on https://demo.smartpay.gsa.gov/about/statistics/
- [ ] Also, should it be XLSX instead of xlsx
- [ ] For the full audits that route to other sites, should we have the external link icon in the button? E.g., https://demo.smartpay.gsa.gov/policies-and-audits/audits/2020-dot-purchase/ and https://demo.smartpay.gsa.gov/policies-and-audits/audits/2019-nsa-travel/)If so, I can log as another issue and list all the ones that need it.

**Comment by klohman** [comment]
> @weiwang-gsa @klohman I took a look at this too because...it's a lot.
> 
> * [ ]  Do we need to add the file size to the xlsx links on https://demo.smartpay.gsa.gov/about/statistics/
Yes, good catch! 

> * [ ]  Also, should it be XLSX instead of xlsx
It should be XLSX. I see that on some of them, but it should be across the board. 

> * [ ]  For the full audits that route to other sites, should we have the external link icon in the button? E.g., https://demo.smartpay.gsa.gov/policies-and-audits/audits/2020-dot-purchase/ and https://demo.smartpay.gsa.gov/policies-and-audits/audits/2019-nsa-travel/)If so, I can log as another issue and list all the ones that need it.
 
Yes, I think we should include the external link icon there as well

**Comment by JessicaMarine1** [comment]
> Yes, I think we should include the external link icon there as well

Done. I added #311

**Comment by klohman** [comment]
@weiwang-gsa 

Not sure if you were working on these as well, but I agree with what Jessica found. 


- On stats page, it should be XLSX. I see that on some of them, but it should be across the board.

-  Add the file size to the xlsx links on https://demo.smartpay.gsa.gov/about/statistics/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
Wowsers. That was a lot. Nice job everyone. Moving to DONE!
