### ISSUE TITLE
Develop "How we work"

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#308]
To help transition work to a new vendor, develop and document "How we work"

Draft: https://docs.google.com/document/d/14g8LF594XcauPN0eTEVy0-pAznIJpFDYK5CFY7blkUE/edit#heading=h.slrfzquh11p6

Note: some items may need to be revisited / developed with vendor

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo this is ready for us to hand off to SmartPay. Since it documents how y'all work we should discuss with the vendor as part of the transition.

For QA -- if you're happy with the content, please Close the issue.

**Comment by rebekahperillo** [comment]
@JessicaMarine1 This is great, thank you for putting the doc together. Moving to CLOSED.
