### ISSUE TITLE
Check hyperlinks

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#309]
- [ ] Manually check all hyperlinks (after launch) on the program site
- [ ] Manually check all hyperlinks (after launch) on the 889 tool

**Comment by vickimcfadden** [comment]
The Fact Sheet (not a SmartPay site) is linked to a 404 - https://demo.smartpay.gsa.gov/files/smartbulletins/smart-bulletin-036.pdf

**Comment by rebekahperillo** [comment]
@JessicaMarine1 Joline and her team are working through the Smart Bulletin updates. It looks like several are ready for posting. I think it's best to launch, then I'll start to upload the new bulletins (double checking that all of the referenced links are correct/working once the new site is launched).

**Comment by rebekahperillo** [comment]
Checked hyperlinks on program and 889 sites. Found one error (on Hawaii's tax information page) and submitted a PR to correct it. 

Smart Bulletins will be addressed in [#357](https://github.com/orgs/GSA/projects/37?pane=issue&itemId=40871153).

Moving to DONE.

**Comment by JessicaMarine1** [comment]
@rebekahperillo i would recommend keeping the issue I open until the link is corrected. Otherwise, you may lose track of what's still pending versus been fixed.

**Comment by rebekahperillo** [comment]
Will do. :)

**Comment by weiwang-gsa** [comment]
@rebekahperillo your PR is merged into staging and ready for you to QA:https://demo.smartpay.gsa.gov/

Please verify if this is all needed for this ticket, and once you finished QA process and  please let us know when you are ready to move it to production. We will have another PR from staging to main at that time, thanks!

**Comment by rebekahperillo** [comment]
I see the changes on the demo site (and now in prod too). Moving to DONE. Thank you!

**Comment by JessicaMarine1** [comment]
Moving to Closed.
