### ISSUE TITLE
How the Program Works

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#31]
Path: how-it-works/
File name: how-gsa-smartpay-works.md
Design: [How It Works > How the Program Works](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A37150&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

Content: https://docs.google.com/document/d/1ZY4ZK4FPdNc75GYmx06R7FWYbUaiy3b6XiUSQg-id60/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
✅ @A-L33. I added some front matter, made some minor edits; it should be ready for you to move if it looks good to you!

**Comment by A-L33** [comment]
@brentryanjohnson I added the video link to the embed text.  Rest looks good!  I'll move this to content ready.

**Comment by brentryanjohnson** [comment]
Content is present in `main`, but dev needs to build paths.

**Comment by mark-meyer** [comment]
@klohman This should be merged into the main branch: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/

**Comment by klohman** [comment]
> @klohman This should be merged into the main branch: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/

The process list headings should be an h3 but the font type looks like it's still using Public Sans. Since it's part of this process list component, maybe it's pulling the font in a little differently, but it should be Merriweather.

**Comment by mark-meyer** [comment]
@klohman Oh, nice catch. I have switched the header and number fonts (these are USWDS variables, so not hard). 

https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/

One thing I noticed that may or may not bother you (it doesn't bother me...but I'm not a designer). Numbers in Merriweather have descenders on 3, 4, 5, 7, and 9 so part sit below the baseline. 6 and 8 also ascend above the X-height. This means vertically centering them visually might be tough — I'm not sure how we would solve that if we wanted to (USWDS already has the centered).

**Comment by klohman** [comment]
> @klohman Oh, nice catch. I have switched the header and number fonts (these are USWDS variables, so not hard).
> 
> https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/
> 
> One thing I noticed that may or may not bother you (it doesn't bother me...but I'm not a designer). Numbers in Merriweather have descenders on 3, 4, 5, 7, and 9 so part sit below the baseline. 6 and 8 also ascend above the X-height. This means vertically centering them visually might be tough — I'm not sure how we would solve that if we wanted to (USWDS already has the centered).

Yeah I see what you mean about the descenders, but I don't think it's enough of a visual problem to warrant trying to create a USWDS hack. I think it's good.

**Comment by klohman** [comment]
@rebekahperillo Ready for your review

**Comment by rebekahperillo** [comment]
Looks great! Moved to "Done"! :)
