### ISSUE TITLE
External link icon

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#311]
External link icon is needed on `View full audit` button that routes to an external site:

- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2020-dot-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2019-nsa-travel/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2019-dod-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2019-dod-air-force-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2018-gao/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2018-dod-purchase-travel/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2018-cigie-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2018-dos/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2017-gao-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2017-epa-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2017-usps-fleet/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2017-va-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-gao-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-gao-travel/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-dod-travel/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-epa-travel/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-dhs-purchase/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2016-doi-purchase-fleet/
- [ ] https://demo.smartpay.gsa.gov/policies-and-audits/audits/2015-gao-purchase/

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://demo.smartpay.gsa.gov/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
@klohman @weiwang-gsa 

Also, if it's an external site that links to a PDF, I assume it shows the PDF, # pages, and the external site icon. Like here: 

https://demo.smartpay.gsa.gov/policies-and-audits/audits/2014-va-purchase/

Assuming that's the case, everything looks good, so I'm moving to DONE. Thank you!
