### ISSUE TITLE
State Taxes | Uncapitalize "State"

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#323]
To be consistent with the SmartPay style guide, uncapitalize the word "State" for each state tax page.  See below example from Arizona:

![Image](https://user-images.githubusercontent.com/116583391/267045221-359567be-cf09-4ce2-96bb-6be6c3e80207.png)

Should read: In addition to a state use tax assessed to the cardholder, the state of Arizona can also assess a transaction privilege tax on the merchant.

**Comment by JessicaMarine1** [comment]
@A-L33 this is ready for QA review: demo.smartpay.gsa.gov

**Comment by A-L33** [comment]
Done!
