### ISSUE TITLE
Key Players in the Process

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#33]
Path: stakeholders/key-players
File name: 
Design: [Stakeholders > Key Players](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38379&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Key Players in the Process: https://docs.google.com/document/d/183HMhYegM319D1Hmg_tk7gfi92S2NY3UAI3bA_ieOds/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
✅ Reviewed

**Comment by JessicaMarine1** [comment]
@brentryanjohnson Rebekah updated all this content to be consistent with the training site. Changing the tag back to `Content w/ Ryan` so you can take another look.

**Comment by brentryanjohnson** [comment]
✅ Reviewed

**Comment by mark-meyer** [comment]
@klohman This should be ready for review.

**Comment by klohman** [comment]
@rebekahperillo This page matches the content doc and design, but I'm wondering if we want to keep our language consistent with the updates made to the FAQs and navigation. 

- Should "Agency/Organization Program Coordinators (A/OPCs)" be changed to "Program Coordinators" ? 
- Should "Account Holders" become "Card / Account Holders"?

**Comment by rebekahperillo** [comment]
@klohman 

Let's leave A/OPCs.

Here are some updates for Card/Account Holders

Card/Account Holders
Designated by an agency/organization to receive a card/account.
Secure the payment solution.
Maintain records relating to transactions, as required.
Use the card/account ethically for official government purposes only.

**Comment by klohman** [comment]
> @klohman
> 
> Let's leave A/OPCs.
> 
> Here are some updates for Card/Account Holders
> 
> Card/Account Holders Designated by an agency/organization to receive a card/account. Secure the payment solution. Maintain records relating to transactions, as required. Use the card/account ethically for official government purposes only.

@mark-meyer Couple of content updates from Rebekah ^^

**Comment by mark-meyer** [comment]
@klohman & @rebekahperillo 

This should be updated now: 
https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/stakeholders/

**Comment by rebekahperillo** [comment]
Thank you! Marked as "Done"!
