### ISSUE TITLE
Forum Presentations

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#338]
As a user, I need to access the GSA SmartPay Forum PPT presentations, as well as training videos, so that I'm able to review the training material during the forum and throughout the year.

**Comment by rebekahperillo** [comment]
@CodyHinze @JennaySDavis @felder101 I may need some design and development here. Let's talk about this at standup. Thank you!

**Comment by CodyHinze** [comment]
Added Sprint 22 Label since this will be released with that sprint.
