### ISSUE TITLE
Benefits of the Program

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#34]
Path: about/benefits
File name: benefits.md
Design: [About > Benefits](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A37344&t=NB2CPqpZgPZBO4xz-1)
Template:[ Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452%3A41800&t=NB2CPqpZgPZBO4xz-1)
_______________ 

- Benefits of the program: https://docs.google.com/document/d/1MUSlar3k6ExLfSqZQhMxSABop5AJZqKCnUDgjW6psVY/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa ✅ Reviewed

**Comment by johnbeallgsa** [comment]
@brentryanjohnson Moving to Content Final & Ready

**Comment by brentryanjohnson** [comment]
[🔍 cloud.gov Pages preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/benefits/)

**Comment by rebekahperillo** [comment]
Looks great, approved. Thank you!
