### ISSUE TITLE
BUG - 889 Title Wrapping Issue

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#344]
Expected behavior: I would expect to see the "889 Representations Search" title all on one line (rather than wrapping) for both desktop and mobile.

Current behavior: The 889 Representations Search title is wrapping weirdly on desktop, but not mobile. 

See screenshot from a desktop below:

![Image](https://github.com/GSA/smartpay-website/assets/133424018/d1449887-14ec-45d5-9e1f-2a4972ecfc1c)

**Comment by mark-meyer** [comment]
@rebekahperillo this should be fixed now in staging: 
https://federalist-adaef58d-ff3c-4a0f-961c-c9916e7bff41.sites.pages.cloud.gov/preview/gsa/889-tool/staging/#/
