### ISSUE TITLE
Refunds Overview

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#35]
Path: about/statistics/refunds
File name: refunds.md _and_ refunds-report.md
Design: [About > Stats and Reports > Refunds](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A40714&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked
_______________ 

- Refunds Overview: https://docs.google.com/document/d/19AiGa7IYvVncw1Qr9Qp-SA74U9TNVCjYVKHQfzumMtk/edit#.
- (obsolete) ~~Refund Reporting: https://docs.google.com/document/d/1qmjMCQ224h_9jHZQGW7DssaxZUG1ym7VRZmtGVfJ9Hc/edit#heading=h.qltmvcy0iy7f.~~

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by JessicaMarine1** [comment]
@brentryanjohnson this doc still has some unresolved comments. Not sure if it needs another set of 👀 from you or PO before it should be considered `Final & Ready`

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 The complexity of the text is not ideal, but there's a video that offers a simplified version, so I think we're okay for now.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson do you want to combine these 2 docs and update path & front matter?

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 ✅ 

I've consolidated the content and added a note at the top of the doc.

**Comment by brentryanjohnson** [comment]
[🔍 cloud.gov Pages preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/refunds/)

**Comment by brentryanjohnson** [comment]
We split up `Refunds` and `Refund Reporting` as discussed in standup. :)

**Comment by klohman** [comment]
@brentryanjohnson 

## Design Review notes 
- [GSA SmartPay 3 Master Contract](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/refunds/master-contract/) gives a 404 error. 

- "Footnotes" is a h3 (also with the label "Sources") in the content doc and design. It's an H2 in the preview and displays in the sidenav, which is probably not necessary.

**Comment by brentryanjohnson** [comment]
Thanks, @klohman! The internal link format changed with #154, so I'll go back and fix those.

The footnotes subheading [isn't in the markdown](https://github.com/GSA/smartpay-website/blob/main/src/content/about/refunds.md); it's auto-generated by the markdown plugin. I'll have to figure out if we can change the heading level manually, or if we'll have to edit the plugin to do that. We might end up needing to do them manually instead.

**Comment by JessicaMarine1** [comment]
@klohman can you see if this one is done? it looks like Ryan addressed your prior comments.

**Comment by klohman** [comment]
@rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
