### ISSUE TITLE
Eligibility and the Application Process

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#36]
Path: how-it-works/eligibility
File name: eligibility.md
Design: [How it Works > Eligibility](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A42285&t=NB2CPqpZgPZBO4xz-1)
Template:[Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked
_______________ 

- Content for Who is Eligible at https://docs.google.com/document/d/14Mi4Ko0g_PucbnJ6YIc8SL9gzWIyOj5CFk1oHW2b0_g/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by brentryanjohnson** [comment]
Content is present in `main`, but dev needs to build paths.

**Comment by weiwang-gsa** [comment]
@klohman I think this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/eligibility/

**Comment by klohman** [comment]
@rebekahperillo Ready for your review!

**Comment by rebekahperillo** [comment]
@klohman Are you able to link the new application to the page? https://smartpay.gsa.gov/sites/default/files/GSA%20SMARTPAY%20PROGRAM%20APPLICATION%20updated%2002162023%20(1).pdf

It goes here:
To participate in the GSA SmartPay program, [fill out and submit the application](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/files/gsasmartpay-application.pdf).

**Comment by klohman** [comment]
@weiwang-gsa 

Can you update the application link to this [pdf](https://smartpay.gsa.gov/sites/default/files/GSA%20SMARTPAY%20PROGRAM%20APPLICATION%20updated%2002162023%20(1).pdf)?

We'll need to add this pdf to the new file folder as well.

**Comment by weiwang-gsa** [comment]
@klohman PDF updated, ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/how-it-works/eligibility/

**Comment by rebekahperillo** [comment]
Awesome, thank you! Moving to "Done"!
