### ISSUE TITLE
Updates to Recognizing Your Charge Card Content - Virtual Card Information and Non-SP3 Card Art

### ISSUE THREAD

**Issue by johnbeallgsa** [GSA/smartpay-website#364]
As a user,  I’d like to see policy for virtual and non-SP3 card art under the link below
https://smartpay.gsa.gov/smarttax/recognizing-your-account/#travel-account

Acceptance Criteria:

- [ ] Update the GSA website to indicate that a Non POS card is also exempt.
- [ ] Include information about ghost cards.
- [ ] State not all GSA SmartPay travel cards look alike.

**Comment by rebekahperillo** [comment]
Rebekah is working on this content.

**Comment by rebekahperillo** [comment]
@johnbeallgsa Would you like to check that the content meets the AC? When you're ready you can move it to done. Thank yoU!

**Comment by rebekahperillo** [comment]
@johnbeallgsa Checking in here

**Comment by LoraBradford** [comment]
Reviewed, all AC was meet. Moving to done!
