### ISSUE TITLE
USWDS Update from 3.5.0 to 3.6.1 | Program Site

### ISSUE THREAD

**Issue by rebekahperillo** [GSA/smartpay-website#370]
As an administrator, I want to be sure the program website is up to date with the most current version of the USWDS so that I ensure that our site is accessible.

**Acceptance Criteria**
- [ ] Update the version of USWDS being utilized on the site from 3.5.0 to 3.6.1.

**Comment by JennaySDavis** [comment]
**#203 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass |Update the version of USWDS being utilized on the site from 3.5.0 to 3.6.1. | 




**Comments/Additional Notes**

-   N/A

**ADA Compliance (Automated scan via Chrome Lighthouse)**

| Criteria | Score |
| --- | --- | 
| Performance | 99 |
| Accessibility | 98 |
| Best Practices | 100 |

Tested By Jennifer Davis on 11/6/2023

**Comment by rebekahperillo** [comment]
@felder101 Hi Dan, I assume there is nothing to really view here to QA the story as the changes did not impact the look of our site. Correct?

**Comment by felder101** [comment]
That is correct @rebekahperillo. The check here is to verify the update to dependency did not break any styling on existing pages.

**Comment by rebekahperillo** [comment]
@felder101 Got it, thank you!

**Comment by johnbeallgsa** [comment]
Moving to done. Thank you @felder101
