### ISSUE TITLE
FASCSA Exclusion Link and Language

### ISSUE THREAD

**Issue by johnbeallgsa** [GSA/smartpay-website#373]
As a user, I'd like to find information about the upcoming Federal Acquisition Supply Chain Security Act (FASCSA) of 2018 on the program homepage linked here https://smartpay.gsa.gov/

[FASCA Language Link](https://www.federalregister.gov/documents/2020/09/01/2020-18939/federal-acquisition-supply-chain-security-act)

Link is not available
Alpha Deployment 10/30
User Testing 11/02 - 11/08
Link will go live on Dec. 4th

Acceptance Criteria

 Have link launched on Dec. 4th here https://smartpay.gsa.gov/
 Easy path landing page and provides overview - link to an extract
 Updated language for the link

**Comment by johnbeallgsa** [comment]
Additional AC

Do we add the link under resources under 889 Section or add another column under resources with FASCA



![Image](https://github.com/GSA/smartpay-website/assets/116584037/16079d39-2fb1-4c3d-a6cc-d64622f7c2de)

**Comment by rebekahperillo** [comment]
@johnbeallgsa For this upcoming sprint, we'll need a page to be created under "Resources" so that we have a place to enter the FASCSA content.

**Comment by JennaySDavis** [comment]
This will need to be added to the side navigation as well.

**Comment by CodyHinze** [comment]
Here is a quick mockup of the Navigation link in the "Resources" menu.  The name of this link will likely change 

![Image](https://github.com/GSA/smartpay-website/assets/2073449/9f035910-3a6d-4287-a090-af2078add287)

**Comment by rebekahperillo** [comment]
@felder101 I *think* I created this page and added it to the nav in my own branch. I can show you next week when we're all in the office to make sure we're good to go.

@johnbeallgsa @LoraBradford FYI.

**Comment by rebekahperillo** [comment]
![Image](https://github.com/GSA/smartpay-website/assets/133424018/1fefcd47-a3c7-4a8c-ba30-91c07518cba3)
![Image](https://github.com/GSA/smartpay-website/assets/133424018/3ec67a7b-aba2-4637-8439-38634a78c5d8)

**Comment by rebekahperillo** [comment]
@JennaySDavis @johnbeallgsa This is now available in staging. Please take a look.

@johnbeallgsa When you're ready, you can move this to done. Thank you!

**Comment by JennaySDavis** [comment]
**#373 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Link available under Resources|
| Pass |Listed in the side navigation| 
| Pass | Content for FASCSA displayed.|


**Comments/Additional Notes**
N/A


**ADA Compliance (Automated scan via Chrome Lighthouse)**
|Performance|97|
|Accessibility|100|
|Best Practices|100|

Passed 11/29/23 - JSD

**Comment by johnbeallgsa** [comment]
@JennaySDavis Is there any concern about the Performance score of 97? Would you happen to know what caused it? Do you think this is something that can be addressed or needs to be addressed?

**Comment by JennaySDavis** [comment]
We found the same performance issue with images on the Program Website as on the 889 tool.  I created a user story for us to handle this.

**Comment by johnbeallgsa** [comment]
@rebekahperillo Moving to done with ticket on #378 for performance in future sprint. You all rock!
