### ISSUE TITLE
Logos and Designs

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#38]
Path: about/logos
File name: logos-and-designs.md
Design: [About > Logos](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A40490&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452%3A41800&t=NB2CPqpZgPZBO4xz-1)

- [ ] This issue contains image files that need to be moved over to the new site and linked
_______________ 

- Content from Logos and Designs: https://docs.google.com/document/d/1e4HU0Wt4ijaF57K-7X9JuPwMIQOsapCMZPZxCTGAufk/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
✅ Reviewed

**Comment by johnbeallgsa** [comment]
@brentryanjohnson Moving to content ready for grooming. Thank you!

**Comment by klohman** [comment]
@rebekahperillo 
We were looking at the logos page and had a few questions. 

- Do you have some use case examples you can provide to us on who would be using these logos?
- Are there preferred formats for the downloadable logo? (svg, png?)

cc @brentryanjohnson

**Comment by rebekahperillo** [comment]
Businesses may use the logo/card designs to indicate acceptance of the GSA SmartPay charge cards.

Agencies may reference the logo/card designs to show that they use GSA SmartPay charge cards. 

I'm not aware of the preferred format for download - probably something with a decent quality that can be displayed on websites or marketing materials.

**Comment by klohman** [comment]
@rebekahperillo 

Proposed updated design for this screen. 

We can offer ZIP file downloads that contain multiple formats for each of the image files, which should be beneficial for the use cases you mentioned. This provides more flexibility for how they intend to use these images than the PDF file we currently have. 

![Image](https://github.com/GSA/smartpay-website/assets/18366192/89113e89-fba1-4358-bb51-2d298f735ba5)

cc @brentryanjohnson

**Comment by rebekahperillo** [comment]
@klohman @brentryanjohnson This is great - love the clean look and the option to download multiple file types! Thank you for sharing!

**Comment by rebekahperillo** [comment]
Looks great! Moving to "Done"!
