### ISSUE TITLE
Excel Template Not Downloadable from Smart Bulletin No 30.

### ISSUE THREAD

**Issue by CodyHinze** [GSA/smartpay-website#415]
**Describe the bug**
The Smart Bulletin #30 includes a broken link to an Excel template on page 4.  
* The File Icon below the "REPORTING TEMPLATE" text along with the "OMB Circular No.A-123 CCCM Reporting Template" text should linked to the attached Excel template once hosted in Production.  
* Also, please verify that the hyperlink under the "ADDITIONAL RESOURCES: OMB Circular A-123, Appendix B" directs the user to the correct location.

**To Reproduce**
1. Go to 'Policies and Audits > Smart Bulletins'
2. Click on the file name line under 'No. 030.'
3. Scroll down to page 4 in the PDF and click the like to 'OMB Circular A-123, Appendix B'
* **Current Result:** An error is displayed in the browser or PDF reader.
* **Expected Result:** Excel template should be downloaded

**Proposed Solution**

1. Upload the Excel template to be hosted in an assets folder on the SmartPay Program website.
2. Update the Hyperlink in the SmartPay Bulletin No. 30 PDF to be the URL where the file will be hosted once in Production.
3. Replace the currently hosted Smart Bulletin No. 30 PDF with the new version.

**Testing Notes**

* This bug will not be testable on the staging environment since the PDF URL will include the absolute path of the associated template at its future production location.  URLs used in PDFs require absolute paths that include the full domain. Relative paths can not be used in PDFs. **For verification purposes, a user should hover over the URL and verify the path looks correct on the updated No. 30 PDF file.**

**Comment by CodyHinze** [comment]
New Template:
[AgencyName_ReportingTemplate_OMB_A123_Year.xlsx](https://github.com/GSA/smartpay-website/files/13990705/AgencyName_ReportingTemplate_OMB_A123_Year.xlsx)


Current Smart Bulletin 30 PDF:
[smart-bulletin-030.pdf](https://github.com/GSA/smartpay-website/files/13990704/smart-bulletin-030.pdf)

**Comment by CodyHinze** [comment]
Design Review/Testing on Staging
1. **PASSING** -- New version of the SMART BULLETIN NO. 030 PDF downloads
2. **PASSING** -- Link in the Smart Bulletin PDF points to: "https://smartpay.gsa.gov/files/AgencyName_ReportingTemplate_OMB_A123_Year.xlsx"
3. **PASSING** -- Manually changing the URL path to the Demo site works to download the excel template at "https://demo.smartpay.gsa.gov/files/AgencyName_ReportingTemplate_OMB_A123_Year.xlsx" 

Passing - CLH - Moving to Ready for QA.

**Comment by CodyHinze** [comment]
Updated the PDF to remove the blank page (page 5). 

**Here is a copy of the updated file.** 
[smart-bulletin-030.pdf](https://github.com/GSA/smartpay-website/files/14040243/smart-bulletin-030.pdf)

**Comment by johnbeallgsa** [comment]
Looks great, moving to Done.
