### ISSUE TITLE
Audit Repository

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#44]
Path: policies-and-audits/audits
File name: 
Design: [Policies & Audits > Audit Repo](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A35816&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Audits at https://docs.google.com/document/d/1D-mG798sHOSjhtV8AaCLwV9VGFOb2AvL6igZnbDoQGc/edit

**Comment by JessicaMarine1** [comment]
@brentryanjohnson this is ready for your review.

**Comment by brentryanjohnson** [comment]
✅ Reviewed @A-L33

**Comment by A-L33** [comment]
@brentryanjohnson I just accepted all changes.  You had 3 notes; one for engineering, one re: PDFs, and one about tables.  Anything I need to address immediately?  Or is this good to go for development?

**Comment by brentryanjohnson** [comment]
I think it's good to go!

**Comment by A-L33** [comment]
Thank you!  Done.

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/policies-and-audits/audits/

**Comment by rebekahperillo** [comment]
Finally through this one! :) Moving to "DONE"! Thank you!
