### ISSUE TITLE
Performance Improvement on GSA Program Landing Page

### ISSUE THREAD

**Issue by JennaySDavis** [GSA/smartpay-website#443]
Based on Lighthouse's findings, the following performance improvements should be implemented:

- Eliminate render-blocking resources - resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles.
- Reduce unused rules from stylesheets and defer CSS not used for above-the-fold content to decrease bytes consumed by network activity.
- 

[Lighthouse Report Viewer_Program_Ticket291.pdf](https://github.com/GSA/smartpay-website/files/14186423/Lighthouse.Report.Viewer_Program_Ticket291.pdf)

**Comment by john-labbate** [comment]
Issue looks to already be resolved, report attached
[lighthouse-2024-08-05.pdf](https://github.com/user-attachments/files/16501127/lighthouse-2024-08-05.pdf)

**Comment by JennaySDavis** [comment]
closing ticket, issues have been resolved with previous development.
