### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#45]
Path: policies-and-audits/policies
File name: 
Design: [Policies & Audits > Policies](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A35644&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked

> - [ ] [OMB Circular A-123 Appendix B pdf](https://smartpay.gsa.gov/sites/default/files/downloads/Issuance-of-Revised-Appendix-B-to-OMB-Circular-A-123.pdf)

- Policies: https://docs.google.com/document/d/1pNglS5XfINHLGBxfoyB_O3y1Wd_Rxh5PSsWVH10YFkg/edit

**Comment by JessicaMarine1** [comment]
@brentryanjohnson this is ready for your review

**Comment by brentryanjohnson** [comment]
✅ Reviewed @A-L33

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo Can you please review the content for this issue and resolve all edits/comments?

**Comment by A-L33** [comment]
Done.  This can proceed.

**Comment by JessicaMarine1** [comment]
@klohman I think for annotation #6 on this one, it should be an external link to that GSA PDF

**Comment by klohman** [comment]
> @klohman I think for annotation #6 on this one, it should be an external link to that GSA PDF

Updated Figma annotation. Also found one PDF that currently links to https://smartpay.gsa.gov/sites/default/files/downloads/Issuance-of-Revised-Appendix-B-to-OMB-Circular-A-123.pdf

**Comment by weiwang-gsa** [comment]
@klohman There are some inconsistency between Figma mock up and edit doc, which one is correct one? 

mock up below:

![Image](https://github.com/GSA/smartpay-website/assets/119954777/64ecc960-908a-48fc-b120-2474c2972160)

There is no M-17-21 in edit doc, instead it is M-17-26:
![Image](https://github.com/GSA/smartpay-website/assets/119954777/ec8fe4b5-2923-4145-851c-bbaec991c30b)

**Comment by klohman** [comment]
@rebekahperillo A concern popped up regarding the length of the policy titles and how they display in the side nav. Long story short, when using the complete policy title, the side nav becomes so long that it is not completely visible and does not appear to scroll. 

#### Proposed solution
For policy titles with parenthetical statements (example: OMB Memorandum M-13-21 (Implementation of the Government Charge Card Abuse Prevention Act of 2012)) 
- we make the policy type and # the h2 - this will appear in the side nav 
- we make the parenthetical an h3, which will not appear in the side nav but will display as a subheading below the policy # 

Mockup example: 
![image](https://github.com/GSA/smartpay-website/assets/18366192/01efd250-b08f-4784-96e3-68b910304d9b)

Let us know if this is a good direction.

**Comment by klohman** [comment]
@rebekahperillo @A-L33 

Here are some mocks for the 2 options we discussed: 

## Option 1 - Grouping by Category 

* I just created Regulations, Memorandums, and Public Laws as the grouping, but we could change that as it makes sense. 
* The side nav links would scroll to the appropriate group 

![Image](https://github.com/GSA/smartpay-website/assets/18366192/ac361169-01cb-4265-a320-30b1cf8dd2a0)

## Option 2 - Table format 
* See [prototype with landing page](https://www.figma.com/proto/bgNCEcglYMCDtEEBys04cx/SmartPay?page-id=1%3A2&type=design&node-id=2401-42418&viewport=323%2C-332%2C0.13&t=pwWEXSFcRTq7cL3r-1&scaling=scale-down-width&starting-point-node-id=2401%3A42418&show-proto-sidebar=1&mode=design) 



![Image](https://github.com/GSA/smartpay-website/assets/18366192/f8bcae3f-3004-42f0-b55a-a5e28ca83e20)

**Comment by weiwang-gsa** [comment]
@klohman @rebekahperillo  the landing page of option 2 looks a little bit odd, Mark just removed the landing page for contacts as it doesn't add much value, I think same thing here as well, but I get it, it just served as landing page for other pages to navigate back, I am not sure if the "Audits Repository" can be 1st menu item of Policies & Audits section, so other pages can navigate back to Audit Repository if it is the 1st item? Not sure which make more sense though. 



![Image](https://github.com/GSA/smartpay-website/assets/119954777/98780469-19c2-453a-80bf-946fe594ffc2)

**Comment by rebekahperillo** [comment]
@klohman @weiwang-gsa Andrew and I both prefer Option 2. I think it'll be easier for users to find relevant policies that way.

It looks like there may be another question here. If you need more input or if it's easier to talk through on a call, just let me know

Thanks to you both!

**Comment by klohman** [comment]
@rebekahperillo @weiwang-gsa 

Two proposals for design solutions for this page:

## 1) Breadcrumb  
* We can use a breadcrumb on the Policies page itself (and we should use this for Smart Bulletins as well). 
* The link for "Policies & Audits" goes to the Policies & Audits landing page 
* The Policies & Audits landing page is not displayed in the global navigation in header. It will only be accessible through these breadcrumbs 

#### Policies page (with breadcrumb) 
![image](https://github.com/GSA/smartpay-website/assets/18366192/eec78201-53ad-4f19-afc2-72735f9f027e)

#### Policies & Audits landing page 
![image](https://github.com/GSA/smartpay-website/assets/18366192/cb910f0b-eeec-4e82-8432-98d3f8b5db24)

## 2) Remove secondary navigation 
Alternatively, we could simply remove the secondary navigation (i.e. the breadcrumbs) from both the Smart Bulletins and the Policies pages. 
* This eliminates the need to create a landing page 
* Users can still navigate to these pages through the global nav in header 
* The Audit page would still contain the side nav that includes Smart Bulletins and Policies
* This breaks our pattern of the secondary navigation (side nav) but is low risk given the availability of global navigation. It may be a better solution to not introduce further complexity and we can see how users interact during usability testing and production usage.

**Comment by weiwang-gsa** [comment]
@klohman since same landing page is used for breadcrumb link, I don't see much difference using breadcrumb than just "Return to Policies and Audits", currently we have one component for top nav, and used for multiple pages, like state tax. If we need to create another component for this, I just feel more customization will make maintenance more complex and make pages pattern inconsistent. If we keep the landing page, it would be better to use original design of Return to xxx, at least page flows are consistent across the site.

**Comment by klohman** [comment]
> @klohman since same landing page is used for breadcrumb link, I don't see much difference using breadcrumb than just "Return to Policies and Audits", currently we have one component for top nav, and used for multiple pages, like state tax. If we need to create another component for this, I just feel more customization will make maintenance more complex and make pages pattern inconsistent. If we keep the landing page, it would be better to use original design of Return to xxx, at least page flows are consistent across the site.
@weiwang-gsa 
You're right there really isn't a difference between the breadcrumbs and the "Return to" link. The only problem with the "Return to" is that they may not have actually come from that page, so the wording is a little misleading. I agree we should be consistent, so whichever path we take, let's apply everywhere. I'll defer to you which is better from a maintenance perspective.

**Comment by weiwang-gsa** [comment]
@klohman for policies full size template, it is missing Date Issued column, does "Date Issued" goes before "Description" or after? when there is no Date Issued, what will be displayed? N/A or empty space?

**Comment by klohman** [comment]
@weiwang-gsa Based on the original content doc, we don't need a Data Issued in the table for Policies.

**Comment by weiwang-gsa** [comment]
@klohman I am little bit confused, google doc still have the date issued though, do you mean all date issued are no longer needed? 


![Image](https://github.com/GSA/smartpay-website/assets/119954777/ebd9a1a7-9bd7-425b-b57e-2b702088a6c2)

**Comment by klohman** [comment]
@weiwang-gsa You're right. I was looking at the first few examples (with no date issued). Let's add it to the left of Description. If we don't have one, let's leave blank for now.

**Comment by rebekahperillo** [comment]
Language for Policies & Audits landing page:

Take a moment to review relevant policies and audit findings to help you build your knowledge about the GSA SmartPay® program and to strengthen your agency's charge card program.

Is this a good start? Or do you need something a bit longer?

@weiwang-gsa @klohman @brentryanjohnson

**Comment by klohman** [comment]
> Language for Policies & Audits landing page:
> 
> Take a moment to review relevant policies and audit findings to help you build your knowledge about the GSA SmartPay® program and to strengthen your agency's charge card program.
> 
> Is this a good start? Or do you need something a bit longer?
> 
> @weiwang-gsa @klohman @brentryanjohnson

Just giving you a glimpse of what it would look like with this content. It's not much, but maybe this is a backlog item to draft meaningful content that could be included here in the future. 

![image](https://github.com/GSA/smartpay-website/assets/18366192/0f48b482-9e46-4312-8dd3-fa67da0eaa50)

**Comment by rebekahperillo** [comment]
I think this is a start. We can build out further if/when we need to. Does that work for the team?

**Comment by klohman** [comment]
@rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
I really like it. Thanks for making the updates @weiwang-gsa and @klohman. Moving to "DONE"! Thank you!
