### ISSUE TITLE
Convert Smart Bulletins from PDF to HTML (Smart Bulletins #17 - # 21 and #23 - #28)

### ISSUE THREAD

**Issue by JennaySDavis** [GSA/smartpay-website#470]
This is linked to the Parent story https://github.com/orgs/GSA/projects/37/views/1?pane=issue&itemId=31304335.  The following Smart Bulletins have been converted from PDF to HTML:
> - [ ] [Smart Bulletin No. 028](https://smartpay.gsa.gov/sites/default/files/SP%20SmartBulletin%20No.%20028%20-%20Record%20Keeping%20Requirements%20(GAO%20Audit%20%2317-276).pdf)
> - [ ] [Smart Bulletin No. 027](https://smartpay.gsa.gov/sites/default/files/SmartBulletin_No027_Identifying_Cost_Savings_Opportunities_in_Purchase_Card_Spend%20(1).pdf)
> - [ ] [Smart Bulletin No. 026](https://smartpay.gsa.gov/sites/default/files/SP%20SmartBulletin%20No.%20026%20-%20FPDS%20Reporting%20Orders%20Under%20MPT%20(1).pdf)
> - [ ] [Smart Bulletin No. 025](https://smartpay.gsa.gov/sites/default/files/SmartBulletin_No025_Record_Retention.pdf)
> - [ ] [Smart Bulletin No. 024](https://smartpay.gsa.gov/sites/default/files/SmartBulletin_No024_Reward_Programs_1.pdf)
> - [ ] [Smart Bulletin No. 023](https://smartpay.gsa.gov/sites/default/files/SP%20SmartBulletin%20No.%20023%20-%20Third%20Party%20Payments_0.pdf)
> - [ ] [Smart Bulletin No. 021](https://smartpay.gsa.gov/sites/default/files/SP%20SmartBulletin%20No.%20021%20-%20%20PL%20112-194%20and%20M-13-21_0.pdf)
> - [ ] [Smart Bulletin No. 020](https://smartpay.gsa.gov/sites/default/files/SP_SmartBulletinNo20_040920_0.pdf)
> - [ ] [Smart Bulletin No. 019](https://smartpay.gsa.gov/sites/default/files/SmartBulletin_No019_Amazon.com_Tax_Exemption_Program.pdf)
> - [ ] [Smart Bulletin No. 018](https://smartpay.gsa.gov/sites/default/files/SP%20SmartBulletin%20No.%20018%20-%20Visa%20Gov't%20Higher%20Ed%20Program%20(1)_0.pdf)
> - [ ] Smart Bulletin No. 017 - https://smartpay.gsa.gov/sites/default/files/FINAL-%20SP_SmartBulletin_No._017-Surcharges_Revised_01102023).pdf

**Comment by john-labbate** [comment]
Noting that SB 27 has a broken link to SB 11, I've updated it to point to where the new page will end up being but it will not work until SB 11 is implemented.

**Comment by john-labbate** [comment]
outstanding issues:
SB 21 – 8 broken links (external) missing table headers and name

**Comment by JennaySDavis** [comment]
**#470 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass | Smart Bulletin #28 |
| Pass | Smart Bulletin #27 |
| Pass | Smart Bulletin #26 |
| Pass | Smart Bulletin #25 | 
| Pass | Smart Bulletin #24 |
| Pass | Smart Bulletin #23 |
| Pass | Smart Bulletin #21 |
| Pass | Smart Bulletin #20 |
| Pass | Smart Bulletin #19|
| Pass | Smart Bulletin #18 |
| Pass | Smart Bulletin #17 |

**Comments/Additional Notes**
Performance score will improve when the following tickets have been implemented: https://github.com/GSA/smartpay-website/issues/443 and https://github.com/GSA/smartpay-website/issues/378

**ADA Compliance (Automated scan via Chrome Lighthouse)**

Criteria | Performance | Accessibility | Best Practice |
| -- | -- | -- | -- |
Smart Bulletin 28 | 98  | 100 | 100 |
Smart Bulletin 27 | 95 | 100 | 100 |
Smart Bulletin 26 | 95 | 100 | 100 |
Smart Bulletin 25 | 96 | 100 |100 |  
Smart Bulletin 24 | 99 | 100 |  100 |  
Smart Bulletin 23 | 100 | 100 | 100 |
Smart Bulletin 21 | 100 | 100 | 100 |
Smart Bulletin 20 | 99 | 100 | 100 |
Smart Bulletin 19 | 96 |100 | 100 |  
Smart Bulletin 18 |98 | 100 | 100 |
Smart Bulletin 17 |95 |100 | 100|



Passed  3/15/24- JSD

**Comment by CodyHinze** [comment]
There is 1 link missing for SB#21

**Comment by LoraBradford** [comment]
Moving to done, acknowledging that the performance score will improve when the following tickets have been implemented: https://github.com/GSA/smartpay-website/issues/443 and https://github.com/GSA/smartpay-website/issues/378. Thank you!
