### ISSUE TITLE
Update USWDS from 3.71 to 3.8 | Program Website

### ISSUE THREAD

**Issue by JennaySDavis** [GSA/smartpay-website#477]
https://github.com/uswds/uswds/releases/tag/v3.8.0

**Comment by CodyHinze** [comment]
The work on this ticket included a Astro template change that affected all pages with Side Navigation. A identical change was made to all pages templates including the templates used by pages in the paths listed below.

The change will be not be noticeable as it is just a code change that duplicates the side bar navigation in code so it is in the correct accessible DOM order in HTML on Mobive devices below the content area of each screen.  

Pages in the following paths were affected and can be used for testing/validation:

- /about/
- /contact/
- /faq/
- /stakeholders/
- /how-it-works/
- /merchants/
- /policies-and-audits/
- /policies-and-audits/audits/
- /resources/forum-presentations/
- /smarttax/state-tax-forms/
- /resources/tools/section-889/
- /404.html

During testing the only noticeable change should be that lAccessibility testing tools like Lighthouse no longer report the side navigation as being outside the reading order on mobile screen sizes.

**Comment by JennaySDavis** [comment]
**#477 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass |Smoke Testing of Program Website system updated USWDS library from  3.71 to 3.8|


**Comments/Additional Notes**
A Link checker was completed on the app - no broken links.


**ADA Compliance (Automated scan via Chrome Lighthouse)**
This USWDS library change has been tested for ADA Compliance with USWDS.


Passed 04/1/2024 - JSD

**Comment by LoraBradford** [comment]
Moving to done, thank you!
