### ISSUE TITLE
Add Meta Description for Smart Bulletin No. 033 - "Prohibited Vendors"

### ISSUE THREAD

**Issue by CodyHinze** [GSA/smartpay-website#478]
One of the most common searches on the SmartPay Program website is for "prohibited vendors." This search does not currently return relevant information. To correct this, we propose adding a meta description to Smart Bulletin No. 033 that includes more relevant terminology based on user searches.

Content should be drafted and added to this ticket prior to implementation

- [ ] The meta description should include "prohibited vendors".

NOTE: Searching for "prohibited vendors" or "Prohibited" should return the Smart Bulletin No. 033 once this feature is implemented and the site is indexed by the search tools.

NOTE: An additional option to explore is adding a FAQ item for Prohibited Vendors that also links to the Smart Bulletin.

**Comment by CodyHinze** [comment]
Proposed META Description for Smart Bulletin 033:

**Smart Bulletin 033 provides guidance to agencies implementing section 889(a)(1)(B) of the John S. McCain National Defense Authorization Act (NDAA). The act prohibits Federal agencies from purchasing products or services from prohibited vendors. You can find a list of prohibited vendors and learn more about how this affects GSA SmartPay program participants.**

**Comment by johnbeallgsa** [comment]
I am good with it. We can add more if needed in the following Sprints. Let's get it added to this Sprint if possible.

**Comment by CodyHinze** [comment]
**Testing on staging:** https://demo.smartpay.gsa.gov/policies-and-audits/smart-bulletins/033/

 
**Acceptance Criteria**
| Pass/Fail | Description |
| --- | --- | 
| Pass | Smart Bulletin No. 033 include a Meta Description in the Head of the HTML page |
| Pass | The meta description should include "prohibited vendors". |


**Accessibility Compliance (Automated scan via Chrome Lighthouse)**
| Criteria | Score |
| --- | --- | 
| Performance | 99 |
| Accessibility | 100 |
| Best Practices | Not Run |

Passed 03/19/2024 - CLH

**Comment by johnbeallgsa** [comment]
Thanks for explaining how to review and for fitting this in during this Sprint! Moving to Done!
