### ISSUE TITLE
Glossary of Terms

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#50]
As a user, I want to know the definitions of terms, so I can understand program or banking specific language in the program, website, and in the master contract.

Acceptance criteria
- User can access content from https://smartpay.gsa.gov/glossary.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 Did your team do a first-round review of this, or are we starting from the current site version?

**Comment by A-L33** [comment]
@brentryanjohnson Sorry Ryan!  This page is TBD for the moment.  We're not sure what the do with this yet.  I mistagged, my apologies!

**Comment by JessicaMarine1** [comment]
Done
