### ISSUE TITLE
Overview of Section 889

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#51]
As a Purchase cardholder, A/OPC, or merchant, I want to access information about Section 889 of the NDAA, so that I can understand and conform with Section 889 requirements.

Acceptance criteria
- User can access content from https://docs.google.com/document/d/1uJ42wFu8zKgfmoQTd8HPt9cN0wX3lGVYaBq1U76MZmQ/edit.

**Comment by JessicaMarine1** [comment]
@brentryanjohnson this one is ready for your review

**Comment by brentryanjohnson** [comment]
@JessicaMarine1 and @johnbeallgsa I think we may have duplicates. Take a look at #53.

**Comment by JessicaMarine1** [comment]
Thanks for flagging @brentryanjohnson. I'll close this as a duplicate

**Comment by JessicaMarine1** [comment]
Duplicate of #53
