### ISSUE TITLE
Program Website Content Changes - May

### ISSUE THREAD

**Issue by JennaySDavis** [GSA/smartpay-website#532]
The following content changes need to be made:
- [ ] [Update recognizing-your-account.mdx](https://github.com/GSA/smartpay-website/commit/479ca044708a61b60937aabbbe9bf5646619b558) 
  - Add 4715 to Purchase and 4615 to Travel so that it matches the Vendor Tax publication.
- [ ] [Update customer-support.mdx](https://github.com/GSA/smartpay-website/commit/7f0652d7f662914a528fe3b93bb0d5e97c65d019) 
  - Removal of Branch language (Changed to Divisions), Updated Titles for Tri Thai and Erin VanDagna
- [ ] [Update events.md](https://github.com/GSA/smartpay-website/commit/84f162fa280e77e859e584044b08dff16c7fa0d2) 
  - Change the Smart Bulletin 022 from a PDF link to the new SB 022 page "policies-and-audits/smart-bulletins/022/"
- [ ] [Update customer-support.mdx](https://github.com/GSA/smartpay-website/commit/2067dd78056670bcb0fa8785139097e4ec9d3da5) 
  - Removed Judy
- [ ] [Update statistics.md](https://github.com/GSA/smartpay-website/commit/ec992a2afe9bf294e16c9c37b12a739e8ffe820b) 
  - Removed Second Registered Mark on SmartPay based on style guide.
- [ ] [Update 032.md](https://github.com/GSA/smartpay-website/commit/e8f97074202c4e8dd58be4b15af5a407a8e7965a) 
  - Change case of VISA to Visa.
- [ ] [Update 038.md](https://github.com/GSA/smartpay-website/commit/3de6992a03c956c54774488198c60d9512f84574) 
  - Fixed Typos in Bulletin, U.S. Bank, and Mastercard
- [ ] [Update 037.md](https://github.com/GSA/smartpay-website/commit/44d321eb4c4842f5fb89e9c27ef47f8f181265d5) 
  - Updates for style guide, See Google Sheet, Style Guide Content Updates Tab --> https://docs.google.com/spreadsheets/d/1KpWhazh_STQtvpGinJKBAqTWhh-QQcLdOxfnDVSGDZo/edit?usp=sharing .

**Comment by JennaySDavis** [comment]
**#532 Acceptance Criteria**
 

| Pass/Fail | Description |
| --- | --- | 
| Pass| Update recognizing-your-account.mdx (https://github.com/GSA/smartpaywebsite/commit/479ca044708a61b60937aabbbe9bf5646619b558) |
| Pass |  Add 4715 to Purchase and 4615 to Travel so that it matches the Vendor Tax publication. Update customer-support.mdx](https://github.com/GSA/smartpay-website/commit/7f0652d7f662914a528fe3b93bb0d5e97c65d019) |
|  Pass | [Update customer-support.mdx](https://github.com/GSA/smartpaywebsite/commit/7f0652d7f662914a528fe3b93bb0d5e97c65d019) 
  Removal of Branch language (Changed to Divisions), Updated Titles for Tri Thai and Erin VanDagna|
 | | 


**Comments/Additional Notes**



**ADA Compliance (Automated scan via Chrome Lighthouse)**
| Criteria | Score |

N/A 


Passed 05/13/2024- JSD


The following content changes need to be made:
- [ ] [Update recognizing-your-account.mdx](https://github.com/GSA/smartpay-website/commit/479ca044708a61b60937aabbbe9bf5646619b558) 
  - Add 4715 to Purchase and 4615 to Travel so that it matches the Vendor Tax publication.
- [ ] [Update customer-support.mdx](https://github.com/GSA/smartpay-website/commit/7f0652d7f662914a528fe3b93bb0d5e97c65d019) 
  - Removal of Branch language (Changed to Divisions), Updated Titles for Tri Thai and Erin VanDagna
- [ ] [Update events.md](https://github.com/GSA/smartpay-website/commit/84f162fa280e77e859e584044b08dff16c7fa0d2) 
  - Change the Smart Bulletin 022 from a PDF link to the new SB 022 page "policies-and-audits/smart-bulletins/022/"
- [ ] [Update customer-support.mdx](https://github.com/GSA/smartpay-website/commit/2067dd78056670bcb0fa8785139097e4ec9d3da5) 
  - Removed Judy
- [ ] [Update statistics.md](https://github.com/GSA/smartpay-website/commit/ec992a2afe9bf294e16c9c37b12a739e8ffe820b) 
  - Removed Second Registered Mark on SmartPay based on style guide.
- [ ] [Update 032.md](https://github.com/GSA/smartpay-website/commit/e8f97074202c4e8dd58be4b15af5a407a8e7965a) 
  - Change case of VISA to Visa.
- [ ] [Update 038.md](https://github.com/GSA/smartpay-website/commit/3de6992a03c956c54774488198c60d9512f84574) 
  - Fixed Typos in Bulletin, U.S. Bank, and Mastercard
- [ ] [Update 037.md](https://github.com/GSA/smartpay-website/commit/44d321eb4c4842f5fb89e9c27ef47f8f181265d5) 
  - Updates for style guide, See Google Sheet, Style Guide Content Updates Tab --> https://docs.google.com/spreadsheets/d/1KpWhazh_STQtvpGinJKBAqTWhh-QQcLdOxfnDVSGDZo/edit?usp=sharing .

**Comment by LoraBradford** [comment]
Thank you for all of these changes, moving to done!
