### ISSUE TITLE
Bank Contact Information

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#55]
Path: contact/banks-contact
File name: 
Design: [Contact > Bank Contact](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A64785&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Bank contact info: https://docs.google.com/document/d/11dTm9B7Q8eX-cbyx_2HOlVZ62xYMiTGa4yuKI3E8Cik/edit.

**Comment by mark-meyer** [comment]
@klohman this is ready for you! https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/contact/banks/

**Comment by klohman** [comment]
@rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
@mark-meyer @klohman 

The flow for the "Contact" page is confusing for me.

Under "Bank Contact Information", I think we should have:

Card/account holders, please contact your agency’s issuing bank directly about:

Specific account issues.
How to use the bank’s online account access website.
Changes to address or personal information change.
Payment.
Delinquency.
Confusion about your bill.
Disputed transactions.
The GSA SmartPay® team does not have the ability to look up any account information.

Then, nested under "Bank Contact Information" have the "GSA SmartPay 3® Contractor Banks" information (eliminating the "Agency Bank Information" heading).

GSA SmartPay 3® Contractor Banks
For specific account questions, please see the contact information for the banks below.

Citibank
800-790-7206 (within United States)
904-954-7850 (collect calls from outside United States)
[Citibank Online Account Access](https://home.cards.citidirect.com/CommercialCard/Cards.html) (self register, commercial site).

U.S. Bank
888-994-6722 (within United States) Note: To speak with a live person, do not press any buttons.
701-461-2232 (collect calls from outside United States)
[U.S. Bank Online Account Access](https://access.usbank.com/cpsApp1/index.jsp) (self register, commercial site).

WEX
866-939-4472

To learn which bank/brand provides your agency’s GSA SmartPay 3 services, please email [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

If card/account holders require assistance with contacting the bank or with agency-specific charge card/account related issues, please reach out to your agency’s program coordinator (A/OPC).

**Comment by klohman** [comment]
@rebekahperillo 

Take a look at the revised mockup for the Bank Contact Information page, based on your edits. This would then eliminate the "Agency Contact Information" page and I've removed that as well from the sidenav (if I understand you correctly).

![image](https://github.com/GSA/smartpay-website/assets/18366192/39e9463e-6e6b-423c-b821-6af946ebc6a7)

**Comment by rebekahperillo** [comment]
@klohman Yes, this is on track, thank you. You can add the "GSA SmartPay 3® Contractor Banks" under "Bank Contact Information" on the left nav too.

Also the word "about" is missing on the first line. And the "/" has spaces before/after in some cases, but not all on the page. Not sure if this stuff is in an issue or not.

If you have questions, let me know. :)

**Comment by rebekahperillo** [comment]
OH and this line is missing too (it's in the copy that I provided above).

To learn which bank/brand provides your agency’s GSA SmartPay 3 services, please email [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

Again, I don't know if this matters now or not.

**Comment by klohman** [comment]
@rebekahperillo Updated Bank Contact Information - please confirm if this is correct. 

![image](https://github.com/GSA/smartpay-website/assets/18366192/4e15f56b-aec5-4123-8879-4e8b4a9f1a2e)

**Comment by mark-meyer** [comment]
@klohman with other engineers out, I tagged you in a PR for these changes. Here's a preview branch: 

https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/mmeyer/55-revise-contact/contact/

If it looks okay to you, I'll merge it in. Thank you!

**Comment by JessicaMarine1** [comment]
@rebekahperillo this is ready for your re-review.

**Comment by rebekahperillo** [comment]
Moving to "Done". Thank you for making these updates!
