### ISSUE TITLE
Team Contact Information

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#57]
As a user, I want contact information for specific CCCM employees, so I can contact them directly.

Acceptance criteria
- User has access to team contact information available at https://docs.google.com/document/d/1HCMYUgESnTa7tOSS9o6zUVVdYVsNzFsuG5WqmLJ3I9w/edit.

**Comment by johnbeallgsa** [comment]
@brentryanjohnson Ready for your review.

**Comment by johnbeallgsa** [comment]
@brentryanjohnson I removed the YouTube Video - Moving to Content Ready for Grooming

**Comment by JessicaMarine1** [comment]
Closing issue. Same content is contained in #56
