### ISSUE TITLE
Merchant Information Overview

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#58]
Path: merchants/merchant-overview
File name: 
Design: [Merchants](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38473&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked
_______________ 

- Content: https://docs.google.com/document/d/1JDCqMp6uJ-b5ozMVjTNDcMRhfyQlzMxgHPuSJ6ImVZg/edit.

**Comment by brentryanjohnson** [comment]
✅ Reviewed @johnbeallgsa

**Comment by A-L33** [comment]
Reviewed with Ryan.  Good to go.

**Comment by klohman** [comment]
@rebekahperillo This is ready for QA review.

**Comment by rebekahperillo** [comment]
Looks great! Moved to "Done"!
