### ISSUE TITLE
Cardholder FAQs

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#60]
Path: 
File name: 
Design: 
Template:
_______________ 
As a cardholder, I want easy access on this website to common questions I might have, so I don't have search the entire website or contact customer service.

Acceptance criteria
- User is presented with content from https://docs.google.com/document/d/11Ris6nI7NjGb5U-3sOYphD8T3--GFDowH4cypEir5HA/edit.
- Content in accordions is searchable even in its collapsed state. The USWDS component demo doesn't seem to allow for this OOTB, but the [ada.gov](http://ada.gov/) implementation does support search in accordions: https://www.ada.gov/topics/intro-to-ada/#the-ada-prohibits-disability-discrimination-in-many-areas-of-life

**Comment by johnbeallgsa** [comment]
@brentryanjohnson ready for review

**Comment by JessicaMarine1** [comment]
@brentryanjohnson did you review this one? It doesn't look like you signed off on the doc and there is no comment passing it from you to PO. Going to re-tag it as `Content w/ Ryan` until you confirm.

**Comment by brentryanjohnson** [comment]
✅ Reviewed @johnbeallgsa

**Comment by JessicaMarine1** [comment]
Moved to #16
