### ISSUE TITLE
Merchant FAQs

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#62]
Path: 
File name: 
Design: 
Template:
_______________ 
As a merchant, I want easy access on this website to common questions I might have, so I don't have search the entire website or contact customer service.

Acceptance criteria
- User is presented with content from https://docs.google.com/document/d/1QLBvyI1_fHIvyFvQTDFiTP3soxixTgr8JKQ1HIses8Y/edit.
- Content in accordions is searchable even in its collapsed state. The USWDS component demo doesn't seem to allow for this OOTB, but the [ada.gov](http://ada.gov/) implementation does support search in accordions: https://www.ada.gov/topics/intro-to-ada/#the-ada-prohibits-disability-discrimination-in-many-areas-of-life

**Comment by brentryanjohnson** [comment]
✅ Reviewed @johnbeallgsa

**Comment by A-L33** [comment]
Done!

**Comment by JessicaMarine1** [comment]
Moved to #16
