### ISSUE TITLE
Publications & Videos landing page

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#63]
Path: resources/publications/
File name: 
Design: [Resources > Pubs & Vids](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A36881&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________

- Content: https://docs.google.com/document/d/1EYDhvUPfrNE5nmajhsTvq0rK4yZDnGcehBrGiYpDpUQ/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by weiwang-gsa** [comment]
@klohman per our discussion, I will put path as resources/publications for now, I tag Ryan in the google docs just in case my assumption is wrong.

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/publications/

**Comment by klohman** [comment]
@weiwang-gsa There's one small typo on the **Fleet Publications** heading

<img width="330" alt="Screen Shot 2023-07-21 at 8 08 39 AM" src="https://github.com/GSA/smartpay-website/assets/18366192/eb570ae6-fe5e-4caf-8581-c6854301cf31">

**Comment by JessicaMarine1** [comment]
@klohman I fixed this in Wei's absence. It's ready for your re-review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/publications/

**Comment by klohman** [comment]
@rebekahperillo Ready for your review

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
