### ISSUE TITLE
Purchase Publications

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#64]
Path: resources/publications/purchase
File name: 
Design: [Resources > Pubs & Vids > Purchase](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A45817&t=NB2CPqpZgPZBO4xz-1)
Template: [Full-Width Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-42390&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel/word files that need to be moved over to the new site and linked

> - [ ] [Helpful Hints for Purchase Account Use pdf](https://smartpay.gsa.gov/sites/default/files/downloads/19-00249_19%20SmartPay%20Purchase%20Helpful%20Hints_508C.pdf) **This is linked from several pages
> - [ ] [Pre-Approval/Approval Request Template Word doc](https://smartpay.gsa.gov/sites/default/files/Pre-Approval%20Request.docx)
> - [ ] [Pre-Approval Response Template Word doc](https://smartpay.gsa.gov/sites/default/files/Pre-Approval%20Response.docx)
> - [ ] [Approval Response Template Word doc](https://smartpay.gsa.gov/sites/default/files/Approval%20Response.docx) 
> - [ ] [Blanket Approval Authority Template Word doc](https://smartpay.gsa.gov/sites/default/files/Blanket%20Approval%20Authority.docx)
> - [ ] [Approving Official Approvals Log Excel doc](https://smartpay.gsa.gov/sites/default/files/AO%20Approval%20Tracking%20Log.xlsx)

_______________ 

- Purchase Pubs: https://docs.google.com/document/d/1BeWqaJ4nu0UsZgoMYJSiaFjNmRbFqYa6wbHFHXjK7QM/edit#.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by JessicaMarine1** [comment]
@johnbeallgsa @A-L33 this has unresolved comments. Moving back to `Content w/ PO`

**Comment by A-L33** [comment]
@JessicaMarine1 Ready to go.

**Comment by JessicaMarine1** [comment]
@klohman this one is missing annotations on the page

**Comment by klohman** [comment]
> @klohman this one is missing annotations on the page

@JessicaMarine1 Updated Figma annotations and added document descriptions in AC. 

Most of the documents on this page are Word documents currently (and one Excel), if we have a plan to handle these differently than PDFs.

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
