### ISSUE TITLE
Travel Publications

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#65]
Path: resources/publications/travel
File name: 
Design:[ Resources > Pubs & Vids > Travel Publications](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A36960&t=NB2CPqpZgPZBO4xz-1) 
Template: [Full-Width Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-42390&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked

> - [ ] [GSA FedRooms Card Sleeve pdf](https://smartpay.gsa.gov/sites/default/files/downloads/05-19-00614%20508%20HR.pdf)
> - [ ] [GSA SmartPay Tax Advantage Travel Card pdf]( https://smartpay.gsa.gov/sites/default/files/SP3_Tax_Advantage_Travel_Card_AcctHandout_v3-1-2019_020823.pdf) **This is linked from several pages
> - [ ] [Helpful Hints for Travel Account Use pdf](https://smartpay.gsa.gov/sites/default/files/downloads/19-00248_19%20SmartPay%20Travel%20Helpful%20Hints_508C.pdf) **This is linked from several pages
> - [ ] [Managing your SmartPay Travel Program pdf](https://smartpay.gsa.gov/sites/default/files/19-00260_SmartPay_Travel-Flipbook_508C_020823.pdf)
> - [ ] [SmartTax Customer Guide pdf](https://smartpay.gsa.gov/sites/default/files/downloads/19-00262_SmartPay_Smart%20Tax_SS_508C.pdf)
> - [ ] [Travel Card Troubleshooting Guide pdf](https://smartpay.gsa.gov/sites/default/files/downloads/19-00265_SmartPay_Travel-Guide_HIRES.pdf)

_______________ 

- Travel Pubs: https://docs.google.com/document/d/1vU6gIt_QxzNbUdB1xQmtodpddL_wgC-v3QkEXnzcdFs/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by JessicaMarine1** [comment]
@klohman I don't think this one is done being annotated.

**Comment by klohman** [comment]
> @klohman I don't think this one is done being annotated.

Updated Figma annotation and added PDFs to the story description

**Comment by weiwang-gsa** [comment]
@klohman Online Flipbook has no descriptions/Types/Types/CMLS? It kinda looks odd without anything 



![Image](https://github.com/GSA/smartpay-website/assets/119954777/2b47d3c6-efe1-4794-a84c-0b013c5325bb)

**Comment by klohman** [comment]
@weiwang-gsa Good catch. 

Looking back at the content doc, the Online Flipbook actually belongs to the row above (Managing Your GSA SmartPay Travel Program), and we should move the link to the Flipbook to the Type column after PDF.  The content of the flipbook and the PDF are the same, just different formats. 

Here's a mockup. 
![image](https://github.com/GSA/smartpay-website/assets/18366192/aa1ea8da-43f3-4863-b307-36752f963719)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/publications/travel/

**Comment by klohman** [comment]
@rebekahperillo ready for QA review

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!

**Comment by rebekahperillo** [comment]
@weiwang-gsa PDF for you....



[publications-guidiance-for-emergency-situation.pdf](https://github.com/GSA/smartpay-website/files/12163202/publications-guidiance-for-emergency-situation.pdf)

**Comment by rebekahperillo** [comment]
@weiwang-gsa Also, it looks like guidance is spelled incorrectly in the title. Just noticed!
