### ISSUE TITLE
All Business Line Publications

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#67]
Path: resources/publications/all-business-lines
File name: 
Design: [Resources > Pubs & Vids > All](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A45935&t=NB2CPqpZgPZBO4xz-1)
Template: [Full-Width Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-42390&t=ZdXxtCQnJUFtcq4C-4)

- [ ] This issue contains PDFs/Excel files that need to be moved over to the new site and linked

> - [ ] [Chip and PIN/Signature Card pdf](https://smartpay.gsa.gov/sites/default/files/EMV%20Slipsheet%20High%20Resolution%20FINAL.pdf)
> - [ ] [Fighting Fraud with Knowledge](https://smartpay.gsa.gov/sites/default/files/downloads/19-00263_SmartPay_Fraud%20Prevention_508C.pdf)
> - [ ] [GSA SmartPay Strategic Payment Solutions](https://smartpay.gsa.gov/sites/default/files/downloads/19-00264_SmartPay%20Payment_Folder_wSlipsheets_508.pdf)
> - [ ] Guidance for Management and Use of Government Charge Cards in Emergency Situations **This is currently in PPTX format and we need an updated PDF version 

_______________
> - [ ] All Business Lines Pubs: https://docs.google.com/document/d/1mWqBZzkA9aVB3fxEXV9huAwZutnD4w43H3o8snvRDtU/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
✅ Reviewed

**Comment by weiwang-gsa** [comment]
@rebekahperillo @A-L33 @klohman  Guidance for Management and Use of Government Charge Cards in Emergency Situations is still PPT version in google doc, is there a PDF version? Also, the emergency card FAQ is pdf file, should we link it to this PDF file or should it link to FAQ page, if FAQ page, which section it should link to?

**Comment by weiwang-gsa** [comment]
@rebekahperillo Thank you so much! @klohman: this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/publications/all-business-lines/

**Comment by klohman** [comment]
@rebekahperillo Ready for QA

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
