### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#68]
Path: resources/publications/videos
File name: 
Design: [Resources > Pubs & Vids > Videos](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A45994&t=NB2CPqpZgPZBO4xz-1)
Template: [Full-Width Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-42390&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Videos: https://docs.google.com/document/d/1z_odAx1hLHk8ra7IWuwHdY1vpI8DVViVoUIJovr8iyQ/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
I reviewed this one and reformatted to reduce repetition, but there's a broken link. See comment in doc.

**Comment by A-L33** [comment]
Link fixed.  Moving to ready.

**Comment by JessicaMarine1** [comment]
@klohman take a look at the annotations on this one. There aren't any numbers on the actual page and I think it might be a copy/paste error. These are videos, not PDFs.

**Comment by klohman** [comment]
> @klohman take a look at the annotations on this one. There aren't any numbers on the actual page and I think it might be a copy/paste error. These are videos, not PDFs.

Figma annotations updates

**Comment by mark-meyer** [comment]
@klohman Here are the videos: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/publications/videos/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
