### ISSUE TITLE
GSA SmartPay Forum

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#69]
Path: events/gsa-smartpay-forum
File name: 
Design: [Events > Forum](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A66069&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Content: https://docs.google.com/document/d/1BHONVHzsf-QbqAykbKtSvfa7GojPK_vHJYlkOw9mr_8/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa ✅ I took a first pass!

**Comment by johnbeallgsa** [comment]
@brentryanjohnson - First pass looked great!  Moving to Content Ready for Grooming.  Thank you!

**Comment by weiwang-gsa** [comment]
@klohman question, figma design have events as page title, should it be "GSA SmartPay Forum" instead? 

![Image](https://github.com/GSA/smartpay-website/assets/119954777/bf58daf0-d7c3-477c-a586-fa9e8dfdbd59)

**Comment by klohman** [comment]
@weiwang-gsa 
It looks like Events should be nested under the Resources section. I would leave the page title as "Events" and just have the GSA SmartPay forum as an h2. They don't have any other events to list, so I think that's why we thought we'd just be linking to a GSA SmartPay forum page. 

I'd be ok with the path being resources/events. If we want to pause this until Ryan is back to get his input, I'm ok with that too.

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/resources/events/

**Comment by klohman** [comment]
@weiwang-gsa 

Events page looks good. One thing we'll need to change is on the homepage, the "Go to events" link points to the old path (/gsa-smartpay-forum) and is giving a 404 error. We should point that to resources/events

**Comment by weiwang-gsa** [comment]
@klohman home page issue resolved, ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
