### ISSUE TITLE
Program Statistics Overview

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#70]
Path: about/statistics-overview
File name: statistics-overview.md
Design: 
Template:
_______________ 
As a user, I want access to an overview of program statistics and a summary overview of program statistics,  so I can quickly see total spend through the GSA SmartPay program.

Acceptance criteria
- User has access to content on https://docs.google.com/document/d/1QCKgQU8Jns3MK0hzN87RUDJXJu1JfC-uF2t4LwFWwsM/edit#.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
✅ Reviewed

**Comment by johnbeallgsa** [comment]
@brentryanjohnson Moving to Content Ready for Grooming

**Comment by JessicaMarine1** [comment]
Moved to #141
