### ISSUE TITLE
Stats Tool

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#71]
Path: about/statistics/statistics-tool
File name: statistics-tool.md
Design: 
Template:
_______________ 
As a user, I want specific agency level transaction details, so I can access aggregate reporting for the program.

Acceptance criteria
- User has access to content on https://docs.google.com/document/d/1qmjMCQ224h_9jHZQGW7DssaxZUG1ym7VRZmtGVfJ9Hc/edit#heading=h.qltmvcy0iy7f.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa 
✅ Reviewed!

**Comment by JessicaMarine1** [comment]
Moved to #141
