### ISSUE TITLE
Refund Reporting

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#72]
Path: about/statistics/refunds-report
File name: refunds-report.md
Design: 
Template:
_______________ 
As a user, I want high-level information about refunds, so I can understand how the government is earning refunds and why it is allowable by law and policy.

Acceptance criteria
- User has access to content on https://docs.google.com/document/d/1DiqsJ3naYNnfztsvFlX6P1sKqk_Ro0ZuRfsDtTg9ZwA/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@johnbeallgsa I reviewed this one, but it looks like it's missing a link ("under development").

**Comment by A-L33** [comment]
Ready.  We have an aggregate graph.  It's not great and we may have some clean up to do after launch, but it should work for our purposes.

**Comment by JessicaMarine1** [comment]
Moved to #35
