### ISSUE TITLE
Purchase Card FPDS Reports

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#73]
Path: about/statistics/purchase-report
File name: purchase-report.md
Design: 
Template:
_______________ 
As a user, I want access to FPDS reporting, so I can view FPDS data and it is required by the FAR.

Acceptance criteria
- User can access content and downloadable links on https://docs.google.com/document/d/1W_pfb8TX-gwqC6ju9atkr-ZJoDXrnUJmmULqggZvmPU/edit#heading=h.3d9bgv6pfswu.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
✅ Reviewed
@johnbeallgsa Ideally, we'd have a better way to reference FAR and other regulatory citations (as opposed to in the body copy), but I don't think that made it into the first round of the style guide. Perhaps we can return to it later. 👍

**Comment by JessicaMarine1** [comment]
Moved to #141
