### ISSUE TITLE
Strategic Payment Solutions

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#88]
Path: about/strategic-payment-solutions
File name: strategic-payment-solutions.md
Design: [Strategic Payment Solutions](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A40421&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452%3A41800&t=NB2CPqpZgPZBO4xz-1)
_______________ 

- Content: https://docs.google.com/document/d/1IhCVidDFkx0EZejNlpBvM1iVWQYwa4qr9Yap3KIiM1E/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
[🔍 cloud.gov Pages preview](https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/about/strategic-payment-solutions/)

**Comment by rebekahperillo** [comment]
Looks good, approved!
