### ISSUE TITLE
Account Holder Responsibilities

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#89]
Path: stakeholders/account-holders
File name: 
Design: [Stakeholders > Cardholder Responsibilities](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A42655&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

Content: https://docs.google.com/document/d/19RzLqoqd7lzug1R0z_l9kRM-tScHzcnMkRE0UuhxWeM/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by mark-meyer** [comment]
@klohman this is ready for design review. https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/stakeholders/account-holders/

**Comment by klohman** [comment]
@rebekahperillo Ready for review.

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
