### ISSUE TITLE
Program Coordinator Responsibilities

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#90]
Path: stakeholders/program-coordinators
File name: 
Design: [Stakeholders > A/OPC Responsibilities](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1425%3A42593&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Content: https://docs.google.com/document/d/1eFVkipSfvg2NDap7egx0tEzAU2rh34RCvJYMnxRiK68/edit#.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
@A-L33 ✅ Initial review complete!

**Comment by mark-meyer** [comment]
@klohman This should be ready for review.
https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/stakeholders/program-coordinators/

**Comment by klohman** [comment]
@rebekahperillo This is ready for review. 

Note (for future content updates), there is frequent use of "A/OPC" on this page, inconsistent with the title "Program Coordinator."

**Comment by rebekahperillo** [comment]
Thank you, Kristen! Moving to "Done"!
