### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#95]
Path: events
File name: 
Design: 
Template:
_______________ 
As a user, I want information about other events, so I can attend those events if they are revelant to me.

Acceptance criteria
- User is presented content from https://docs.google.com/document/d/1EesEQP8r_ptxVogqqEMxNqyqV_kK-oTQP3QeYswRWu4/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
Thanks, @JessicaMarine1. I think we might need to table this one for now. cc @johnbeallgsa 

This is more of a template for events than a page of content; it has a structure, but no content. It also isn't necessarily a specific page, so the metadata isn't predictable.

I think this should become a separate, slightly more expansive issue, addressing the following:

- Should events and news be combined into a single content type?
- Should events have a custom design pattern distinct from what we've developed so far?
- Should events have individual pages, or a combination (such as a calendar, or list of several events)?
- Does event content expire when the event is over, or does the content remain even when the event has passed? If the latter, for how long?

**Comment by JessicaMarine1** [comment]
Because this is more of a template for _future_ content, rather than current content needing review, I removed the `Content w/ Ryan` tag.

**Comment by JessicaMarine1** [comment]
@A-L33 @brentryanjohnson Just bringing this one to your attention. Since it's more of a _template_ for future content, rather than any current content needing review, it might be appropriate to move to `Content Final & Ready` so that Ryan can account for it in his IA.

**Comment by A-L33** [comment]
I am in agreement unless @brentryanjohnson has concerns.

**Comment by JessicaMarine1** [comment]
No separate "Events" page for MVP; will go directly to forum event
