### ISSUE TITLE
IBA/CBA Information

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#98]
As a user, I want information about differentiating IBAs and CBAS, so I know how to treat the accounts from a taxation perspective.

Acceptance criteria
- User can access content from https://docs.google.com/document/d/1gjwCPzFz0fIBNO9lpesy6haLEhOUVn1uy985gGKmuVk/edit.

**Comment by A-L33** [comment]
@brentryanjohnson Ready for review.

**Comment by brentryanjohnson** [comment]
✅ Reviewed
@johnbeallgsa I didn't add front matter to this one because it will likely not be its own page, but rather a block of content that can be reused on multiple pages.

**Comment by JessicaMarine1** [comment]
Content captured elsewhere.
